--       _________ __                 __
--      /   _____//  |_____________ _/  |______     ____  __ __  ______
--      \_____  \\   __\_  __ \__  \\   __\__  \   / ___\|  |  \/  ___/
--      /        \|  |  |  | \// __ \|  |  / __ \_/ /_/  >  |  /\___ \
--     /_______  /|__|  |__|  (____  /__| (____  /\___  /|____//____  >
--             \/                  \/          \//_____/            \/
--  ______________________                           ______________________
--                        T H E   W A R   B E G I N S
--         Stratagus - A free fantasy real time strategy game engine
--
--      (c) Copyright 2013-2019 by Andrettin
--
--      This program is free software; you can redistribute it and/or modify
--      it under the terms of the GNU General Public License as published by
--      the Free Software Foundation; either version 2 of the License, or
--      (at your option) any later version.
--
--      This program is distributed in the hope that it will be useful,
--      but WITHOUT ANY WARRANTY; without even the implied warranty of
--      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--      GNU General Public License for more details.
--
--      You should have received a copy of the GNU General Public License
--      along with this program; if not, write to the Free Software
--      Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--

DefineText("The Ethnology of Germany II", {
	Author = "H. H. Howorth",
	Publisher = "The Journal of the Anthropological Institute of Great Britain and Ireland, vol. 7",
	Year = 1878,
	InitialPage = 211,
	CopyrightNotice = "This text is in the public domain in the United States because it was published prior to 1923. It is also in the public domain in Austria, as the last surviving author has died more than 70 years ago (in 1923).",
	Chapters = {
		{
			"name", "The Ethnology of Germany, Part II: The Germans of Cæsar",
			"text", {
				"tetanising ingredient. Professor Leverridge of Sydney University, has obtained an alkaloid from the substance used in Efaté Island (New Hebrides), which was innocuous to guinea pigs. Professor Halford of Melbourne University, has failed to produce any bad symptoms on dogs and rabbits with the same substances used by me. These gentlemen have all arrived at similar conclusions, viz., that the tetanus observed after wounds by these poisoned arrows, is the ordinary traumatic disease, and not the result of the poison on the arrows.\n\tWe may therefore, I think, in the meantime, be justified in looking upon these reputed poisons with the greatest doubt as to their potency. At the same time, it may be premature to state positively that none of the substances used by the South Pacific Islanders possess poisonous properties. But that these natives possess a poison that will produce a disease identical with traumatic tetanus, after an interval of five or ten days, and after only a short contact with the living body, is a fact yet to be proved.\n\n\tThe Director then read the following paper, in the absence of the Author.\n\n~<The Ethnology of Germany, Part II.~>\n~<The Germans of Cæsar.~> By H. H. Howorth, Esq., F.S.A.\n\nThe first Germans whom Cæsar encountered were the Germans ruled over by Ariovistus. His army was not a mere collection of warriors making a raid across the Rhine, but was apparently a migration of a whole people, consisting of six confederate tribes. Such migrations became frequent enough two or three centuries later, and had we sufficient information about the earlier period, we should doubtless find that they were common enough then also. They are not to be explained by a mere wanton habit of wandering. It is not for this cause that whole peoples desert their hearths, desert the homeland endeared to them as their birth-place, containing the sacred fanes of their gods and the graves of their ancestors. They moved because they were compelled to move, either by the pressure of physical circumstances or of more vigorous tribes; and it was doubtless one of such causes that set the people of Ariovistus in motion. As we shall see presently, the time at which he lived was marked by the aggressive advance of the great Suevic or Suabian race in central Germany; and just as this was the cause of the migration of the Tencteri, the Usipetes and the Ubii, so I believe it to have been the cause of the migration of Ariovistus and his people. The confederacy which he led con-",
				
				"sisted of the tribes named Harudes, Marcomanni, Tribocci, Vangiones, Nemetes, Sedusii and Suevi. The Suevi doubtless forming only a contingent, being one of those contingents mentioned by Caesar, which they were accustomed to send out annually for purposes of plunder.\n\tThe Harudes again were apparently no part of the original invaders. They came in afterwards, as Ariovistus himself told the Sequani (vide infra); we may therefore discard them for the present. The Suevi again belonged to another kingdom, they were merely a contingent of the main race in central Germany ruled over by Nasua and Cimber, as Caesar says. (I, 37.) These also we may for the present discard.\n\tWe have left five tribes, the Marcomanni, Nemetes, Tribocci, Vangiones and Sedusii. The Marcomanni bear a name meaning originally Marchmen or Mercians, but applied by the classical authors just as the term Mercia was by our early chroniclers, in no generic sense, but specifically to the ancient inhabitants of Bohemia. They were, I believe, the ancestors of the modern Bavarians.\n\tThe Marcomanni formed a powerful empire in central Germany, which a few years later was ruled over by Maroboduus; and it is exceedingly unlikely that they should as a body have migrated at this time into Gaul, or that Ariovistus should have been their king. They doubtless, like the Suevi, furnished a contingent to the invading host, a posse of that warlike youth which was ever ready for an excursion if fighting and plunder might be expected.\n\tWe have left for consideration the tribes of the Nemetes, Tribocci, Vangiones and Sedusii. They were, I believe, the special subjects of Ariovistus, and the Germans proper of Caesar's first book. Let us first say a few words about the name German. It is, in the first place, not a native name. The people of Germany called themselves Deutsch, and Grimm, Zeuss, and others are at one in urging that it is a name applied by outsiders to the people of Gerinany. In the next place, it is a generic name, applied not only to the people of the upper Rhine, but also to those of the lower Rhine. Thus Caesar, speaking of certain tribes there, says the Condrusi, Eburones, Caercesi, Pcemani, who were collectively known as Germani (II, 4); and in another place he speaks of the Segni and the Condrusi of the race of the Germans. (VI, 32.) We find the name occurring also far from the Teutonic frontier of Gaul, and in fact on its opposite borders, for we read in Pliny of a tribe living on the Iberian frontier of Gaul called the Oretani, who he says were also called Germani. (Pliny, III, 3.) Ptolemy tells us their chief town was called Oreton Germanon. (Zeuss p. 59.)",
				
				"\tWe may go a step further, and in examining the neighbours of Gaul on the side of Germany, we shall find that the name German was not applied to them all, but only to a certain portion of them: thus Tacitus says, speaking of the people of the middle Rhine, \"Quidam ut in licencia vetustatis, plures deo ortos pluresque gentis appellationes Marsos, Gambrivios, Suevos, Vandilios affirmant eaque vera et antiqua nomina. Ceterum Germaniæ vocabulum recens et nuper additum, quoniam qui primi Rhenum transgressi Gallos expulerint ac nunc Tungri tunc Germani vocati eunt. Ita nationis nomen, non gentis evaluisse paulatim, ut omnes primum a victore ob metum mox a se ipsis invento nomine Germani vocarentur.\" (Tacitus, \"Germ.,\" II.)\n\tAgain the term Germani is used in early times in a very loose way; indeed, so much so, that in a passage of Seneca, \"consol. ad Helv.,\" VI, and others of Pliny, Par. 4, and Dio. 5, 3, 12, it was apparently applied to Celtic tribes.\n\tTacitus argues that the name was adopted by those who were styled Germans from their victories, \"ita nationis nomen, non gentis evaluisse paulatim, ut omnes primum a victori ob metum mox a se ipsis invento nomine Germani vocarentur\" (\"Germ.,\" II); and it has been suggested that the name may be connected with such a word as guerre-man or war-man; but Zeuss, whose etymological instinct, and whose knowledge of Celtic and German was profound, disclaims a Teutonic explanation of the name, and says that the explanation of Tacitus, like the parallel explanations of the names Suevi and Vandilii, which he derives from the names of their gods, is not probable; and he argues with considerable force, that when Tacitus himself says that those who were formerly called Tungri, were named Germani after crossing the Rhine and coming in contact with the Celts, that he shows the name was adopted from their new neighbours, just as the Slavic tribes adopted the name Wends from their Teutonic neighbours. (\"Die Deutsche,\" etc., 60.) Zeuss shows that if the name were connected with the French guerre, or the German wirre (confusion) or wehre, the old German weri or wari, the name ought to be Virromani or Varimanni, and not Germani (id., 59, note); nor does he countenance the derivation from the old German man's name Germ, another form of Gorm or Guthrum, whence we have the local names Germenze or Germize in the Lorsch annals. (Id.)\n\tCæsar is the first author who uses the name for trans-Rhenane peoples; before his time its use was clearly very uncertain; thus Aristotle is quoted by Stephen of Byzantium as naming a tribe Germani, which he tells us was of Celtic race. (Id., 60.)\n\tIn the Fasti Capitolini, a famous chronicle of Roman affairs, reaching from 120 A.U.C. to 765 A.U.C., we read, in the year",
				
				"222 B.C., M. Claudius M.F., M. N. Marcellus, An. DXXXI Cos. de Galleis Insubribus et Germaneis K. Mart. isque spolia opi (ma) rettulit duce hostium Vir (domaro ad Cla) stid (ium interfecto) (Grævius, \"Thes. Antt. Rom.,\" II, 227; Zeuss, loc. cit.) Polybius, who describes this event, speaks of the allies of the Insubres as Gaesati, and tells us they were mercenaries from the Rhone Valley. (Id.) The term Germani therefore here, as in the case of the Tungri, seems to be an appellative, and in this case perhaps applied to a Celtic tribe; for the names of its leaders, as given by Polybius, are, as Zeuss has shown, Celtic; they were, Kogkolitanos and Aneroestos. On the other hand, it would seem that the upper part of the Rhone Valley was in early times occupied by certain tribes whose Teutonic affinities are not improbable, and whom we hope to treat of in a future paper. It is these tribes to whom Livy applies the term \"semi- Germani.\" (21-38.) The burden of my argument is to show that the name Germani was not indigenous to the Teutonic tribes themselves. This view seems to be now held by all the best authorities. The most general notion among these same authorities is, that the name is of Celtic origin, and was given to the Teutonic peoples by their neighbours the Gauls. The term Celtic is in this case vague, and may include a good deal from the Romans themselves to the Belgæ. With this extension of the term Celtic, I am disposed to think that the view that the name Germani is of Celtic origin is a true one. That the name was the usual and ordinary name however given by the Gauls to their neighbours beyond the Rhine, I cannot so readily admit. The French name for Germany is Allemagne, and for Germans Les Allemands, and I have small doubt that these are old Gallic names for the country and the people, as I shall argue when we come to treat of the Allemanni. What if the name Germani be Latin, and originated with the Romans themselves? Germanus is a very good and ancient Latin word, meaning brother, and Festus connects it with that Latin root which we have adopted into English in the word germ and germination; while the very word itself in its sense of close relationship is used constantly in the phrase cousin-german. Varro ap. Serv ad Virg. V, 412, explains Germani as meaning that the individuals answering to the description were sprung from the same genitrix. In the sense of brother or close relation the word is used by the earlier writers, such as Virgil, Cicero and Terence, and so essentially Latin is it, that it occurs in several puns, as for instance in regard to two consuls who had a mutual struggle. \" De Germanis non de Gallis duo triumphant consules.\" (Velleius II, 67.) Cicero makes a similar joke about a Cimbrian who killed his brother, \"Germanum Cimber occidit\" (\" Cic. ap",

				"" -- to do: add the rest of the article
			}
		}
	}
})
