--       _________ __                 __
--      /   _____//  |_____________ _/  |______     ____  __ __  ______
--      \_____  \\   __\_  __ \__  \\   __\__  \   / ___\|  |  \/  ___/
--      /        \|  |  |  | \// __ \|  |  / __ \_/ /_/  >  |  /\___ \
--     /_______  /|__|  |__|  (____  /__| (____  /\___  /|____//____  >
--             \/                  \/          \//_____/            \/
--  ______________________                           ______________________
--                        T H E   W A R   B E G I N S
--         Stratagus - A free fantasy real time strategy game engine
--
--      (c) Copyright 2013-2021 by Andrettin
--
--      This program is free software; you can redistribute it and/or modify
--      it under the terms of the GNU General Public License as published by
--      the Free Software Foundation; either version 2 of the License, or
--      (at your option) any later version.
--
--      This program is distributed in the hope that it will be useful,
--      but WITHOUT ANY WARRANTY; without even the implied warranty of
--      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--      GNU General Public License for more details.
--
--      You should have received a copy of the GNU General Public License
--      along with this program; if not, write to the Free Software
--      Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--

DefineLiteraryText("the_poetic_edda", {
	Chapters = {
		{
			"name", "Atlakvitha En Grönlenzka",
			"text", {
				"~<Atlakvitha En Grönlenzka~>\n\n~<The Greenland Lay of Atli~>\n\n~<Introductory Note~>\n\nThere are two Atli poems in the ~<Codex Regius~>, the ~<Atlakvitha~> (Lay of Atli) and the ~<Atlamol~> (Ballad of Atli). The poems are not preserved or quoted in any other old manuscript, but they were extensively used by the compilers of the ~<Volsungasaga~>. In the manuscript superscription to each of these poems appears the word \"Greenland,\" which has given rise to a large amount of argument. The scribe was by no means infallible, and in this case his statement proves no more than that in the period round 1300 there was a tradition that these two poems originated in the Greenland settlement.\n\nThe two Atli poems deal with substantially the same material: the visit of the sons of Gjuki to Atli's court, their deaths, and the subsequent revenge of their sister, Guthrun, Atli's wife, on her husband. The shorter of the two, the ~<Atlakvitha~>, tells the story with little elaboration; the ~<Atlamol~>, with about the same narrative basis, adds many details, some of them apparently of the poet's invention, and with a romantic, not to say sentimental, quality quite lacking in the ~<Atlakvitha~>. Both poems are sharply distinguished from the rest of the collection by their metrical form, which is the Malahattr (used irregularly also in the ~<Harbarthsljoth~>), employed consistently and smoothly in the ~<Atlamol~>, and with a considerable mixture of what appear to be Fornyrthislag lines (cf. Introduction) in the ~<Atlakvitha~>.\n\nIt is altogether probable that both poems belong to the eleventh century, the shorter ~<Atlakvitha~> being generally dated from the first quarter thereof, and the longer ~<Atlamol~> some fifty years or more later. In each case the poet was apparently a Christian; in the ~<Atlamol~> (stanza 82) Guthrun expresses her readiness to die and \"go into another light,\" and in the ~<Atlakvitha~> there is frequent use of mythological names (~<e.g.~>, Valhall, Hlithskjolf) with an evident lack of understanding of their relation to the older gods. These facts fit the theory of a Greenland origin exceedingly well, for the Greenland settlement grew rapidly after the first explorations of Eirik the Red, which were in 982-985, and its most flourishing period was in the eleventh century. The internal evidence, particularly in the case of the ~<Atlamol~>, points",

				"likewise to an origin remote from Iceland, Norway, and the \"Western Isles\"; and the two poems are sufficiently alike so that, despite the efforts of Finnur Jonsson and others to separate them, assigning one to Greenland and the other to Norway or else where, it seems probable that the manuscript statement is correct in both instances, and that the two Atli poems did actually originate in Greenland. An interesting account of this Greenland settlement is given in William Hovgaard's ~<Voyages of the Norsemen to America~>, published by the American-Scandinavian Foundation in 1914, and an extraordinarily vivid picture of the sufferings of the early settlers appears in Maurice Hewlett's ~<Thorgils~>, taken from the ~<Floamannasaga~>.\n\nFrom the standpoint of narrative material there is little that is distinctively Norse in either the ~<Atlakvitha~> or the ~<Atlamol~>. The story is the one outlined in the prose ~<Drap Niflunga~> (largely based on these two poems), representing almost exclusively the southern blending of the Attila and Burgundian legends (cf. introductory note to ~<Gripisspo~>). In the ~<Atlakvitha~>, indeed, the word \"Burgundians\" is actually used. Brynhild is not mentioned in either poem; Sigurth's name appears but once, in the ~<Atlamol~>. Thus the material goes directly back to its South-Germanic origins, with little of the Northern making-over which resulted in such extensive changes in most parts of the Sigurth story. The general atmosphere, on the other hand, particularly in the ~<Atlamol~>, is essentially Norse.\n\nAs has been said, the ~<Atlakvitha~> is metrically in a chaotic state, the normal Malahattr lines being frequently interspersed with lines and even stanzas which apparently are of the older Fornyrthislag type. How much of this confusion is due to faulty transmission is uncertain, but it has been suggested that the composer of the ~<Atlakvitha~> made over in Malahattr an older Atli poem in ~<Fornyrthislag~>, and this suggestion has much to recommend it. That he worked on the basis of an older poem is, indeed, almost certain, for in oral prose tradition a far larger number of distinctively Norse traits would unquestionably have crept in than are found in the material of the ~<Atlakvitha~>. As for the ~<Atlamol~>, here again the poet seems to have used an older poem as his basis, possibly the ~<Atlakvitha~> itself, although in that case he must have had other material as well, for there are frequent divergences in such matters as proper names. The translation of the ~<Atlakvitha~> is rendered peculiarly difficult ",

				"by the irregularity of the metre, by the evident faultiness of the transmission, and above all by the exceptionally large number of words found nowhere else in Old Norse, involving much guesswork as to their meanings. The notes do not attempt to indicate all the varying suggestions made by editors and commentators as to the reconstruction of defective stanzas and the probable meanings of obscure passages; in cases which are purely or largely guesswork the notes merely point out the uncertainty without cataloguing the proposed solutions.\n\n__________________\n\nGuthrun, Gjuki's daughter, avenged her brothers, as has become well known. She slew first Atli's sons, and thereafter she slew Atli, and burned the hall with his whole company. Concerning this was the following poem made:\n\n1. Atli sent | of old to Gunnar\nA keen-witted rider, | Knefröth did men call him;\nTo Gjuki's home came he | and to Gunnar's dwelling,\nWith benches round the hearth, | and to the beer so sweet.\n\n[~<Prose~>. On the marriage of Guthrun to Atli at the instigation of her brothers, Gunnar and Hogni, and on the slaying of Atli and his two sons, Erp and Eitil, cf. ~<Drap Niflunga~> and note.\n\n1. Line 1 apparently is in Fornyrthislag. ~<Knefröth~> (the name is spelt in various ways, and its meaning is uncertain): in the ~<Atlamol~> (stanza 4) there are two messengers, one named Vingi and the other unnamed; the annotator combines the two versions in the ~<Drap Niflunga~>. ~<Benches~>, etc.: the adjective rendered \"round the hearth,\" which etymologically it ought to mean, is made obscure by its application to \"helmets\" in stanzas 3 and 17.]",

				"2. Then the followers, hiding | their falseness, all drank\nTheir wine in the war-hall, | of the Huns' wrath wary;\nAnd Knefröth spake loudly, | his words were crafty,\nThe hero from the south, | on the high bench sitting:\n\n3. \"Now Atli has sent me | his errand to ride,\nOn my bit-champing steed | through Myrkwood the secret,\nTo bid You, Gunnar, | to his benches to come,\nWith helms round the hearth, | and Atli's home seek.\n\n4. \"Shields shall ye choose there, | and shafts made of ash-wood,\nGold-adorned helmets, | and slaves out of Hunland,\n\n[2. ~<Falseness~>: i.e., Gunnar's followers concealed their fear and hatred of the Huns at the feast; but the word may mean \"fear of treachery.\" ~<War-hall~>: the word used is \"Valhall,\" the name of Othin's hall of slain warriors.\n\n3. ~<Myrkwood the secret~> (the adjective is literally \"unknown\") the which divided Atli's realm from that of the Gjukungs; cf. ~<Oddrunargratr~>, 23 and note. ~<Around the hearth~>: the adjective is the same one which is applied to \"benches\" in stanza 1 (cf. note); it may be an error here, or it may possibly have the force of \"of your followers,\" i.e., Gunnar is to arm the men of his household (those who are round his hearth) for the journey.\n\n4. ~<Slaves~>, etc.: some editions have \"swords in plenty.\" ~<Scarlet~>: the word apparently means \"slaughter-red,\" \"blood-red,\" but it may mean something entirely different.]",

				"Silver-gilt saddle-cloths, | shirts of bright scarlet,\nWith lances and spears too, | and bit-champing steeds.\n\n5. \"The field shall be given you | of wide Gnitaheith,\nWith loud-ringing lances, | and stems gold-o'er-laid,\nTreasures full huge, | and the home of Danp,\nAnd the mighty forest | that Myrkwood is called.\"\n\n6. His head turned Gunnar, | and to Hogni he said:\n\"What thy counsel, young hero, | when such things we hear?\nNo gold do I know | on Gnitaheith lying\nSo fair that other | its equal we have not.\n\n7. \"We have seven halls, | each of swords is full,\n\n[5. ~<Gnitaheith~>: here the dragon Fafnir had his lair (cf. ~<Gripisspo~>, 11). Sigurth doubtless owned it after Fafnir's death, and the Gjukungs after they had killed Sigurth. Possibly they had given it to Atli in recompense for the death of his sister, Brynhild, and he now offered to restore it to them, or--as seems more likely--the poet was not very clear about its ownership himself. ~<Stems~>: i.e., the gilded stems of ships, carved like dragons,--an evident northern touch, if the word is correct, which is by no means certain . ~<Danp~>: this name was early applied to a mythical Danish king (cf. ~<Rigsthula~>, 49 and note) but it may have been fabricated by error out of the word \"DanparstaÞir\" (the phrase here used is \"staÞi Danpar\"), used in the ~<Hervararsaga~> of a field of battle between the Goths and the Huns, and quite possibly referring to the region of the Dnieper. The name seems to have clung to the Atli tradition long after it had lost all definite significance. ~<Myrkwood~>: cf. note on stanza 3.]",

				"(And all of gold | is the hilt of each;)\nMy steed is the swiftest, | my sword is sharpest,\nMy bows adorn benches, | my byrnies are golden,\nMy helm is the brightest | that came from Kjar's hall,\n(Mine own is better | than all the Huns' treasure.)\"\n\n~<Hogni spake:~>\n8. \"What seeks she to say, | that she sends us a ring,\nWoven with a wolf's hair? | methinks it gives warning;\nIn the red ring a hair | of the heath-dweller found I,\nWolf-like shall our road be | if we ride on this journey.\"\n\n9. Not eager were his comrades, | nor the men of his kin,\n\n[7. The stanza is clearly in bad shape; the manuscript indicates line 5 as beginning a new stanza. In line 5 the manuscript has \"and shield\" after \"helm.\" ~<Kjar~>: Gering ingeniously identifies this Kjar with Kjar the father of Olrun, mentioned in the ~<Völundarkvitha~>, introductory prose and stanza 2, on the basis of a genealogy in the ~<Flateyjarbok~>, in which Authi, the grand father of Kjar (by no means certainly the same man) and Buthli, father of Atli, are mentioned as making a raiding voyage together. This identification, however, rests on slight evidence.\n\n8. The manuscript does not name the speaker. One editor gives the first sentence to Gunnar. ~<She~>, etc.: Guthrun, seeking to warn her brothers of Atli's treachery, sends them a ring with a wolf's hair as a sign of danger; in the ~<Atlamol~> (stanza 4) she sends a message written in runes; cf. ~<Drap Niflunga~>. ~<Heath-dweller~>: wolf.]",

				"The wise nor the wary, | nor the warriors bold.\nBut Gunnar spake forth | as befitted a king,\nNoble in the beer-hall, | and bitter his scorn:\n\n10. \"Stand forth now, Fjornir! | and hither on the floor\nThe beakers all golden | shalt thou bring to the warriors.\n. . . . .  . . . . .\n. . . . .  . . . . .\n\n11. \"The wolves then shall rule | the wealth of the Niflungs,\nWolves aged and grey-hued, | if Gunnar is lost,\nAnd black-coated bears | with rending teeth bite,\nAnd make glad the dogs, | if Gunnar returns not.\"\n\n[9. In line 1 the manuscript has \"His comrades did not urge Gunnar,\" but the name, involving a metrical error, seems to have been inserted through a scribal blunder.\n\n10. The manuscript indicates no lacuna, but probably two lines have dropped out, for the ~<Volsungasaga~> paraphrase runs: \"Give us to drink in great cups, for it may well be that this shall be our last feast.\" ~<Fjornir~>: Gunnar's cup-bearer.\n\n11. Bugge thinks this stanza is spoken by Gunnar's terrified followers; Grundtvig assigns it to Hogni. Apparently, however, Gunnar means that if he and his men are not valiant enough to make the journey and return safely, it matters little what may happen to them. ~<Niflungs~>: regarding the application of this name to Gunnar's Burgundians cf. ~<Brot~>, 17 and note. ~<Bears~>: these \"black\" bears have been used as arguments against the Greenland origin of the poem. ~<And make glad the dogs~>: i.e., by giving them corpses to eat, but the phrase in the original is more than doubtful.]",

				"12. A following gallant | fared forth with the ruler,\nYet they wept as their home | with the hero they left;\nAnd the little heir | of Hogni called loudly:\n\"Go safe now, ye wise ones, | wherever ye will!\"\n\n13. Then let the bold heroes | their bit-champing horses\nOn the mountains gallop, | and through Myrkwood the secret;\nAll Hunland was shaken | where the hard-souled ones rode,\nOn the whip-fearers fared they | through fields that were green.\n\n14. Then they saw Atli's halls, | and his watch-towers high,\n\n[12. Some editions in line 2 read \"home of the Niflungs\" instead of \"their home,\" and others \"home of the Huns,\" the manuscript reading being \"home of the men.\" ~<Heir~>: the ~<Atlamol~> (stanza 28) names two sons of Hogni, Snævar and Solar, both of whom make the journey with their father and are killed. The ~<Volsungasaga~>, combining the two versions, says that Snævar and Solar went with their father, and implies that it was a third and still younger son who said: \"Farewell, and have a good time\" (thus literally).\n\n11. ~<Myrkwood~>: cf. stanza 3 and note; the journey is here made by land, whereas in the ~<Atlamol~> it is made partly by boat; cf. ~<Atlamol~>, 34 and note. ~<Whip-fearers~>: horses, but there is some uncertainty as to the word.\n\n13. In line 1 the manuscript has \"land\" instead of \"halls,\" which involves a metrical error. ~<Watch-towers~>: the word used is identical with the name of Othin's watch-tower, Hlithskjolf (cf. ~<Grimnismol~>, introductory prose). ~<Buthli~>: the manuscript has \"Bikki,\" which has led some editors to transfer this stanza to]",

				"On the walls so lofty | stood the warriors of Buthli;\nThe hall of the southrons | with seats was surrounded,\nWith targets bound | and shields full bright.\n\n15. Mid weapons and lances | did Atli his wine\nIn the war-hall drink, | without were his watchmen,\nFor Gunnar they waited, | if forth he should go,\nWith their ringing spears | they would fight with the ruler.\n\n16. This their sister saw, | as soon as her brothers\nHad entered the hall,-- | little ale had she drunk:\n\"Betrayed art thou, Gunnar! | what guard hast thou, hero,\n'Gainst the plots of the Huns? | from the hall flee swiftly!\n\n17. \"Brother, 'twere far better | to have come in byrnie,\nWith thy household helmed, | to see Atli's home,\n\n[the ~<Hamthesmol~>, placing it between stanzas 16 and 17; it seems more likely, however, that \"Bikki\" was a scribal error for \"Buthli.\" Regarding Bikki cf. ~<Sigurtharkvitha en skamma~>, 63 and note. Line 4 is apparently in Fornyrthislag.\n\n15. Line 1 in the manuscript is apparently incorrectly copied, and some editions omit \"Mid weapons and lances\" and assume a gap in either line 1 or line 3.\n\n17. This may be the remains of two stanzas, the manuscript marks line 5 as beginning a new stanza. Editorial conjectures are]",

				"And to sit in the saddle | all day 'neath the sun,\n(That the sword-norns might weep | for the death-pale warriors,\nAnd the Hunnish shield-maids | might shun not the sword,)\nAnd send Atli himself | to the den of the snakes;\n(Now the den of the snakes | for thee is destined.\n\n~<Gunnar spake:~>\n18. . . . . .  . . . . .\n\"Too late is it, sister, | to summon the Niflungs,\nLong is it to come | to the throng of our comrades,\nThe heroes gallant, | from the hills of the Rhine.\"\n\n* * * * * *\n\n19. Then Gunnar they seized, | and they set him in chains,\n\n[numerous and varied. ~<Household~>: the phrase is the same \"helms round the hearth\" commented on in stanza 3. Some editions insert a conjectural line after line 3. ~<Sword-norns~>, etc.: the line is exceedingly obscure, and the phrase rendered \"sword-norns\" may mean \"corpse-norns.\" Apparently it refers to the warrior-women of the Huns, the \"shield-maids\" of line 5 and of stanza 45. Roman writers refer to the warrior-women among the early Germanic tribes, and the tradition, closely allied to that of the Valkyries, attached itself readily to the ferocious Huns. ~<Den of snakes~>: concerning the manner of Gunnar's death cf. ~<Drap Niflunga~>.\n\n18. The manuscript indicates no lacuna and does not name the speaker; perhaps a line similar to line 1 of stanza 24 (or 26) should be inserted here. ~<Rhine~>: Gunnar's Burgundian home is here clearly localized. After this stanza it is probable that a passage describing the battle has been lost.\n\n19. These two lines, apparently the remains of a full stanza,]",

				"The Burgundians' king, | and fast they bound him.\n\n20. Hogni slew seven | with sword so keen,\nAnd an eighth he flung | in the fire hot;\nA hero should fight | with his foemen thus,\nAs Hogni strove | in Gunnar's behalf.\n\n21. . . . . .  . . . . .\n. . . . .  . . . . .\nThe leader they asked | if his life he fain\nWith gold would buy, | the king of the Goths.\n\n~<Gunnar spake:~>\n22. \"First the heart of Hogni | shall ye lay in my hands,\n\n[may belong after stanza 20. ~<Burgundians' king~>: the phrase may mean \"Burgundians' men,\" i.e., they bound all the Burgundians who were left alive after the battle. This is the only place in the poems in which the name \"Burgundian\" appears; that the poet had no very clear conception of its meaning is indicated by the fact that in stanza 21 he calls Gunnar \"king of the Goths.\"\n\n20. Apparently a Fornyrthislag stanza, though most editions have attempted to expand the lines into Malahattr. The exploits of Hogni (Hagene), with the names of many of his victims, are told in the ~<Nibelungenlied~>. ~<The fire~>: in the Nibelungenlied Kriemhild has the hall set on fire, and the Burgundians fight amid the flames. Line 4 is clearly defective, and some editors regard the name \"Gunnar\" as all that is left of the first two lines of stanza 21.\n\n21. Again apparently the remains of a Fornyrthislag stanza. Editors have attempted various combinations of the lines. ~<Gold~>: presumably Sigurth's treasure.\n\n22. The manuscript does not indicate the speaker; perhaps a first line similar to line 1 of stanza 24 should appear here. Some editors, however, assume that a line is missing after line 3.]",

				"All bloody from the breast | of the bold one cut\nWith ke-en-biting sword, | from the son of the king.\"\n\n23. . . . . .  . . . . .\nThey cut out the heart | from the breast of Hjalli,\nOn a platter they bore it, | and brought it to Gunnar.\n\n24. Then Gunnar spake forth, | the lord of the folk:\n\"Here have I the heart | of Hjalli the craven,\nUnlike to the heart | of Hogni the valiant,\nFor it trembles still | as it stands on the platter;\nTwice more did it tremble | in the breast of the man.\n\n25. Then Hogni laughed | when they cut out the heart\nOf the living helm-hammerer; | tears he had not.\n. . . . .  . . . . .\nOn a platter they bore it, | and brought it to Gunnar.\n\n[Gunnar demands proof that Hogni is dead because, as stanza 29 shows, he is unwilling to die himself until he is assured that the secret of the treasure will perish with him. He did not, of course, intend that the heart should be cut from the living Hogni.\n\n23. Most editions assume a gap (lines 1-2, 2-3 or 3-4). ~<Hjalli~>: Atli's cook, killed to deceive Gunnar, as Atli hoped to wring the secret of the hoard from Hogni if Gunnar remained silent. In the ~<Atlamol~> (stanzas 59-60) Atli's men prepare to kill Hjalli, but he is spared at Hogni's intercession.\n\n25. ~<Helm-hammerer~> (literally \"helmet-smith\"): warrior, i.e., Hogni. No gap indicated in the manuscript.]",

				"26. Then Gunnar spake forth, | the spear of the Niflungs:\n\"Here have I the heart | of Hogni the valiant,\nUnlike to the heart | of Hjalli the craven,\nLittle it trembles | as it lies on the platter,\nStill less did it tremble | when it lay in his breast.\n\n27. \"So distant, Atli, | from all men's eyes,\nShalt thou be as thou | . . . . . from the gold.\n. . . . .  . . . . .\n. . . . .  . . . . .\n\n28. \"To no one save me | is the secret known\nOf the Niflungs' hoard, | now Hogni is dead;\nOf old there were two, | while we twain were alive,\nNow is none but I, | for I only am living.\n\n29. \"The swift Rhine shall hold | the strife-gold of heroes,\nThat once was the gods', | the wealth of the Niflungs,\n\n[26. Line 1 may belong elsewhere (stanzas 18 or 22).\n\n27. Apparently the remains of two Fornyrthislag lines; the manuscript combines them with lines 1-2 of stanza 28. Gunnar foretells Atli's speedy death.\n\n28. Apparently in Fornyrthislag. The manuscript indicates line 3 as the beginning of a stanza, and many editions combine lines 3-4 with stanza 29. This stanza explains Gunnar's demand for Hogni's heart in stanza 22.\n\n29. The manuscript marks line 3, and not line 1, as the beginning of a stanza. ~<Rhine~>, etc.: the stanza shows the blending of]",

				"In the depths of the waters | the death-rings shall glitter,\nAnd not shine on the hands | of the Hunnish men.\"\n\n~<Atli spake:~>\n30. \"Ye shall bring the wagon, | for now is he bound.\"\n\n* * * * * *\n\n31. On the long-maned Glaum | rode Atli the great,\nAbout him were warriors |  . . . . .\nBut Guthrun, akin | to the gods of slaughter,\nYielded not to her tears | in the hall of tumult.\n\n[three different traditions with regard to the treasure: the German tradition of the gold of the Rhine (cf. ~<Völundarkvitha~>, 16, and ~<Sigurtharkvitha en skamma~>, 16), the tradition, likewise German, of the hoard of the Nibelungen (Niflungs), early blended with the first one, and finally the northern tradition of the theft of Andvari's treasure by Othin, Hönir, and Loki (cf. ~<Reginsmol~>, 1-9).\n\n30. Apparently all that is left of a full stanza. The manuscript does not name Atli as the speaker, and Grundtvig inserts: \"Then Atli called, | the king of the Huns,\" as a first line. Some editors combine this line with the two lines of stanza 33. ~<Wagon~>: in ~<Brot~>, 16, Gunnar is led to his death in the serpents' den on horseback, not in a wagon.\n\n31. The stanza in the original is hopelessly confused. ~<Glaum~>: this horse of Atli's is mentioned by name elsewhere. ~<Long-maned~>: uncertain. The manuscript indicates no gap, but something has evidently been lost. ~<Gods of slaughter~>: perhaps the phrase, usually applied to Othin and the other gods, is here used simply to mean \"heroes,\" i.e., Atli, Gunnar, and Hogni. Line 4 suggests Guthrun's tearlessness after Sigurth's death (cf. ~<Guthrunarkvitha II~>, 11)]",

				"Guthrun spake:\n32. \"It shall go with thee, Atli, | as with Gunnar thou heldest\nThe oaths ofttimes sworn, | and of old made firm,\nBy the sun in the south, | by Sigtyr's mountain,\nBy the horse of the rest-bed, | and the ring of Ull.\"\n\n33. Then the champer of bits | drew the chieftain great,\nThe gold-guarder, down | to the place of death.\n. . . . .  . . . . .\n\n34. By the warriors' host | was the living hero\nCast in the den | where crawling about\nWithin were serpents, | but soon did Gunnar\nWith his hand in wrath | on the harp-strings smite;\n\n[32. The manuscript does not indicate the speaker. ~<Sigtyr~> (\"Victory-God\"): Othin; what particular mountain (if any) is meant is unknown. ~<Horse of the rest-bed~>: probably this means \"bedpost,\" i.e., the support of the marriage-bed. ~<Ull~>: the archer god, cf. ~<Grimnismol~>, 5 and note. Nothing is known of his ring.\n\n33. Apparently the remains of a Fornyrthislag stanza. Some editors combine the two lines with the line here indicated as stanza 30. ~<Champer of bits~>: horse. The manuscript indicates no gap.\n\n54. Six Fornyrthislag lines which editors have tried to reconstruct in all sorts of ways. The manuscript marks line 5 as the beginning of a new stanza, Regarding the serpents' den, Gunnar's harp-playing, and the manner of his death, cf. ~<Drop Niflunga~> and ~<Oddrunargratr~>, 27-30, and notes. In ~<Atlamol~>, 62, Gunnar plays the harp with his feet, his hands being bound, and some editors change hand in line 4 to \"foot.\" Lines 5-6 may be interpolated, or, as Bugge maintains, lines 1-4 may have been expanded out of two lines.]",

				"The strings resounded,-- | so shall a hero,\nA ring-breaker, gold | from his enemies guard.\n\n35. Then Atli rode | on his earth-treading steed,\nSeeking his home, | from the slaughter-place;\nThere was clatter of hoofs | of the steeds in the court,\nAnd the clashing of arms | as they came from the field.\n\n36. Out then came Guthrun | to meeting with Atli,\nWith a golden beaker | as gift to the monarch:\n\"Thou mayst eat now, chieftain, | within thy dwelling,\nBlithely with Guthrun | young beasts fresh slaughtered.\"\n\n37. The wine-heavy ale-cups | of Atli resounded,\nWhen there in the hall | the Hunnish youths clamored,\nAnd the warriors bearded, | the brave ones, entered.\n\n[35. The manuscript marks line 3 as beginning a new stanza. Two (possibly three) of the lines appear to, be in Fornyrthislag. ~<Field~>: so the manuscript, involving a metrical error; many editions have \"wood.\"\n\n36. ~<Young beasts~>: Guthrun means Atli's sons, Erp and Eitil, but of course he thinks she refers to newly slaughtered beasts; cf. ~<Guthrunarkvitha II~>, 41-45.\n\n37. ~<Youths~>: a conjectural addition. The brave ones is also conjectural, the manuscript having \"each.\" No gap indicated in the manuscript; some editions insert as line 3 or line 4 a slightly altered version of line 2 of stanza 45.]",

				"38. Then in came the shining one, |  . . . . .\n . . . . . | and drink she bore them;\nUnwilling and bitter | brought she food to the warrior,\nTill in scorn to the white-faced | Atli did she speak:\n\n39. \"Thou giver of swords, | of thy sons the hearts\nAll heavy with blood | in honey thou hast eaten;\nThou shalt stomach, thou hero, | the flesh of the slain,\nTo eat at thy feast, | and to send to thy followers.\n\n40. \"Thou shalt never call | to thy knees again\nErp or Eitil, | when merry with ale;\nThou shalt never see | in their seats again\nThe sharers of gold | their lances shaping,\n(Clipping the manes | or minding their steeds.)\"\n\n41. There was clamor on the benches, | and the cry of men,\n\n[38. No gap indicated in the manuscript, but the two fragments cannot be fitted together as one line. ~<The shining one~>: Guthrun.\n\n39. ~<Giver of swords~>: generous prince, i.e., Atli. ~<Honey~>: cf. ~<Guthrunarkvitha II~>, 42. ~<To~> ~<send~> ~<to~> ~<thy~> ~<followers~>: literally, \"to send from thy high seat.\"\n\n40. Apparently a Fornyrthislag stanza. ~<Merry with ale~>: presumably this refers to Atli, but the manuscript reading makes it apply to the two boys. ~<Sharers of gold~>: princes. Line 5 is either interpolated or all that is left of a separate stanza.\n\n41. The text of the whole stanza has required a considerable amount of emendation. Lines 3-5 may have been expanded out of two lines, or line 5 may be an interpolation, possibly from stanza]",

				"The clashing of weapons, | and weeping of the Huns,\nSave for Guthrun only, | she wept not ever\nFor her bear-fierce brothers, | or the boys so dear,\nSo young and so unhappy, | whom with Atli she had.\n\n42. Gold did she scatter, | the swan-white one,\nAnd rings of red gold | to the followers gave she;\nThe fate she let grow, | and the shining wealth go,\nNor spared she the treasure | of the temple itself.\n\n43. Unwise then was Atli, | he had drunk to wildness,\nNo weapon did he have, | and of Guthrun bewared not;\nOft their play was better | when both in gladness\nEach other embraced | among princes all.\n\n44. With her sword she gave blood | for the bed to drink,\n\n[12 of the ~<Guthrunarhvot~>. ~<Weapons~>: the word literally means \"good-weaving,\" and may refer to silken garments, but this hardly fits the noun here rendered \"clashing.\" ~<Wept not~>: cf. stanza 31 and note.\n\n42. Line 1 appears to be in Fornyrthislag. Guthrun distributes Atli's treasures among his followers apparently to prevent their wrath at the slaying of Erp and Eitil from turning against her; Atli, as stanza 43 shows, is too drunk to realize or prevent what she is doing.\n\n43. The second half of line 4 is apparently an error, but none of the editorial suggestions have improved it.\n\n44. Guthrun allows the dogs and the house-thralls, who had no part in Gunnar's death, to escape before she burns the dwelling]",

				"With her death-dealing hand, | and the hounds she loosed,\nThe thralls she awakened, | and a firebrand threw\nIn the door of the hall; | so vengeance she had.\n\n45. To the flames she gave all | who yet were within,\nAnd from Myrkheim had come | from the murder of Gunnar;\nThe timbers old fell, | the temple was in flames,\nThe dwelling of the Buthlungs, | and the shield-maids burned,\nThey were slain in the house, | in the hot flames they sank.\n\n46. Now the tale is all told, | nor in later time\nWill a woman in byrnie | avenge so her brothers;\nThe fair one to three | of the kings of the folk\nBrought the doom of death | ere herself she died.\n\nStill more is told in the Greenland ballad of Atli.\n\n[with all who are left therein. In ~<Atlamol~>, stanzas 83-84, Atli is slain by a son of Hogni (Hniflung?) with Guthrun's help.\n\n45. Some editions transfer line 2 to stanza 37; others reject line 3 as interpolated. ~<Myrkheim~> (\"Dark-Home\"): probably identical with Myrkwood; cf. stanza 3. ~<Temple~>: probably both here and in stanza 42 the word means little more than the place where Atli's treasures were kept; the poet was by no means literal in his use of terms connected with the heathen religion. ~<Buthlungs~>: sons of Buthli, i.e., Atli and his family. ~<Shield-maids~>: cf. stanza 17 and note.\n\n46. The entire stanza is very likely a later addition. ~<Three kings~>: Atli and his two sons, Erp and Eitil.]"
			}
		},
	}
})
