--       _________ __                 __
--      /   _____//  |_____________ _/  |______     ____  __ __  ______
--      \_____  \\   __\_  __ \__  \\   __\__  \   / ___\|  |  \/  ___/
--      /        \|  |  |  | \// __ \|  |  / __ \_/ /_/  >  |  /\___ \
--     /_______  /|__|  |__|  (____  /__| (____  /\___  /|____//____  >
--             \/                  \/          \//_____/            \/
--  ______________________                           ______________________
--                        T H E   W A R   B E G I N S
--         Stratagus - A free fantasy real time strategy game engine
--
--      (c) Copyright 2013-2019 by Andrettin
--
--      This program is free software; you can redistribute it and/or modify
--      it under the terms of the GNU General Public License as published by
--      the Free Software Foundation; either version 2 of the License, or
--      (at your option) any later version.
--
--      This program is distributed in the hope that it will be useful,
--      but WITHOUT ANY WARRANTY; without even the implied warranty of
--      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--      GNU General Public License for more details.
--
--      You should have received a copy of the GNU General Public License
--      along with this program; if not, write to the Free Software
--      Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--

--	YnglingaSaga = {
--		Title = "~!Ynglinga Saga",
--		Author = "Snorri Sturluson (translated by Samuel Laing)",
--		Year = 1844,
--		Publisher = "London",
--		CopyrightNotice = "This text is in the public domain in the United States because it was published prior to 1923. It is also in the public domain in Austria, as the last surviving author has died more than 70 years ago (in 1868).",
--		Notes = "This text was originally published as part of Samuel Laing's translation of the Heimskringla.",
--		Chapters = {
--		}
--	},
	--[[
	TeutonicMythAndLegend = {
		Title = "~!Teutonic Myth & Legend",
		Author = "Donald A. Mackenzie",
		Year = 1912,
		Publisher = "London: Gresham Publications",
		CopyrightNotice = "This text is in the public domain in the United States because it was published prior to 1923. It is also in the public domain in Austria, as the last surviving author has died more than 70 years ago (in 1936).",
--		Notes = "[Wyrmsun Note: Only selected chapters of this work are included here. Specifically, those in which dwarves are mentioned.]",
		InitialPage = 44,
		Chapters = {
			TheWinterWar = {
				Title = "The Winter War",
				Index = 7,
				Text = {
					"~<Chapter V~>\n\nThe Winter War\n\nThe Great Earthquake--Frost--giants swarm South ward--Njord intervenes--Frey in Power of Giants--Asgard's Archer put to Shame--Peacemakers baffled--Vengeance of Thjasse--Volund--\"Sword of Victory\" forged --Mimer intervenes--Sword captured and Thjasse bound--Coming of Halfdan--Omens at his Birth--The Swords Accursed--Marriage, and Hadding's Birth--Conflicts with Giants--Groa taken Captive--Orvandel--Egil's Trial--The Mythical \"William Tell\"--Birth of Gudhorm--Groa's Promise to Svipdag--Her Incantations--Ull's Boyhood--Svipdag overcome by Halfdan--Visit to Hela--\"Sword of Victory\" recaptured--Svipdag's Great Victory--Thor put to Flight--Halfdan's Death.A great earthquake shook the nine worlds when the winter war was proclaimed. Midgar trembled and the heavens were disturbed. In Asgard the gods heard the dread clamour and the strong walls shivered as with fear. And it was thus that the earthquake was caused. When the sons of Ivalde withdrew their services from the gods, and made compact with their enemies, the terrible Frost-giants, the two giant-maids, Fenja and Menja, seized the handle of the great World-mill and turned it so violently that it went out of order, and disaster was threatened to the Universe. Then southward swarmed the Frost-giants to make war with the gods and their allies.\n\nNow the Vana-god Njord sought to make peace between the gods and the sons of Ivalde, because at that time his son, the sunshine-god, Frey, was with them in northern Alf-heim, where he reigned as a king. He was still but a youth, and the sons of Ivalde had power to do him harm.",

					"With Njord went Bjorno-Hoder, the fair god Balder's brother, the famous archer, who had not yet grown blind. Forsete, Balder's son, was also an envoy, for, like his father, he was a just judge and settler of disputes. Gifted he was with persuasive speech and manners which could subdue the most stubborn disputants. But they discovered that Frey had been given to Beli, \"the howler\", the great giant with enormous body who held him in thrall.\n\nBjorno-Hoder waxed wroth, and he drew his bow to slay Volund-Thjasse and Egil-Orvandel, Ivalde's sons. But Egil-Orvandel was also a great archer, for which he was named Avo. Ere Hoder could shoot, Orvandel's arrow severed his bowstring. Then the god tied the string, and Orvandel's second arrow passed through his fingers without hurting them. Ignoring this dread warning, Balder's brother still persisted, and his third arrow was struck from the bowstring by Orvandel just as he was pulling the string. Thus was Hoder put to shame.\n\nThen the peacemakers turned to take their departure, and Ivalde's sons continued their journey to the north.\n\nThjasse-Volund, son of Ivalde, was filled with boundless vengeance against the gods, and went to his smithy, where he forged the great Sword of Victory. Never was there such a weapon since the beginning of time. It shone like the sun in heaven, and there was no substance that it would not cleave. More terrible was it than Thor's hammer, which the sons of Sindre had made, for he who wielded the sword could prevail over the Thunder-god. Thjasse-Volund was resolved to subdue the gods and conquer Asgard. He also made a ring which multiplied till it became a chain to bind the wind.\n\nBut grave Mimer-Nidhad, who is also called Narve, \"the binder\", came to know of the dread sword which",

					"his rebellious subject had constructed, and he still remained the faithful friend of the gods. He knew well the power possessed by the sword, and feared the disaster which it would cause. So he went to Wolfdales, in Nifel-heim, where Thjasse-Volund had built his, great smithy, and seized the elf-smith, whom he bound with chains. Then The Binder took with him the sword, and also the magic ring from among seven hundred other rings, which it had produced. These he bore unto river-girdled Hela, where he concealed them in his deep cave, heaped with treasure, over which his son was guard. There the sword and the ring were kept until they were recaptured by The Shining One, who prevailed over Thor and became a god in Asgard--Svipdag the Brave, the hero of heroes. But ere that day came many great battles were fought, and mighty warriors perished in their pride.\n\nThe great hero who fought against the giants and Ivalde's sons in the winter war was Halfdan, son of Thor, who by tellers of old tales has also been called Mannus.\n\nAt his birth there were dread omens which foretold his glory and his doom. Eagles screeched, the clamour of thunder was heard, and the shadow of Thor fell over the house. Norns came and twisted the threads of fate. Of gold they made the warp of the web and fastened it under the moon; the ends were hid in the east and the west. One fateful thread was drawn northward towards Jotun-heim, the giants' home, and Urd decreed that it should hold there forever.\n\nHungry ravens cawed one to another, and welcomed the wolf-eyed child who would cause them to thrive with blood and the flesh of slaughtered men. They rejoiced that the battle-feast would soon be spread for them.\n\nHalfdan's mother heard the ravens' song and dreaded",

					"his fate. Two swords there were in her home and they were accursed. She buried them deep in the earth, so that the child, when he grew strong, would not find them. But Halfdan soon displayed his warrior strength. When yet a youth he wrestled with a giant-bear and slew it.\n\nThen came a day when Halfdan found a hidden sword, and in a conflict he slew with it his half-brother, nor did he know it was he. Thus was the sword accursed indeed.\n\nHalfdan had knowledge from his father of sacred runes, and he knew the speech of birds, which gave him advantage over his enemies, for he was warned when danger was at hand.\n\nWhen he grew years of knowledge and strength, he went forth to seek his fortunes. One day he met Signe-Alveig, which means \"nourishing drink\", and her he loved and married. She was the fair swan-maiden whose sister Groa was wed to Egil-Orvandel, son of Ivalde, and their son was Hadding. But although Halfdan lived for long at peace with Ivalde's clan, he fought against them when they leagued themselves with the Frost-giants to combat with the gods and their allies.\n\nA strenuous campaign did Thor's son wage against the Frost-giants on the borders of Midgard, which they sought to possess and put under thrall. The giant Froste was their leader, and with him was Fjalar-Suttung, the fire-giant from Surtur's deep dales. Their march southward Halfdan stayed, and to the bleak north he drave them in confusion. A great battle he fought at Svarin's mound, where he slew Sigbrygg, the sire of his wife and Groa, her sister. Groa he took captive, and he put shame upon her, and with her he took her son Svipdag.\n\nWith Halfdan on his triumphant march northward",

					"went Odin's victorious Valkyries, and nightly the heavens flamed with their splendour, by men called \"The Northern Lights\".\n\nOn the borders of Jotun-heim Halfdan overcame Orvandel-Egil, the great archer, whose house he surrounded in the night.\n\nThen it came about that Halfdan caused Orvandel to make trial of his skill, for hearing he had boasted that he could with the first arrow from his bow hit a small apple placed upon a stick at a great distance, he ordered Svipdag to stand with an apple upon his head.[~<1~>] Then he commanded Orvandel to perform the deed of which he had boasted on penalty of his life, but promised him his freedom if he achieved success.\n\nSvipdag was led forth. To him his sire spoke words of encouragement and good counsel, so that he might bear the trial with courage and unflinchingly, and also lest he should move and thus cause the arrow to miss its mark. Svipdag he made to stand with his back turned so that he might not behold the drawing of the bow.\n\nThree arrows did Orvandel take from his quiver. Then one he aimed at the apple upon his son's head. Careful aim he took and shot it from the bow, and he clove the apple in twain nor harmed his son.\n\nThen did Halfdan ask him why he had taken three arrows from his quiver, and Orvandel-Egil bade him know that it was his purpose, had his son fallen, to slay the man who had compelled the sore trial of skill.\n\nBut the risk was not avenged upon Halfdan until the, day of Svipdag's triumph.\n\nIn sorrow did Groa pass weary days with Halfdan, to whom she bore a son who was named Gudhorm. Then was Groa rejected with deeper shame. When she, with\n\n[~<1~> Saga version of William Tell myth.]",

					"her son, Svipdag, returned to Orvandel, she was heartbroken and had come nigh to life's end. Svipdag she called to her side and told him she must soon die with the sorrow she bore for the death of her sire and the shame that Halfdan had put upon her. Then she told him that he must needs endure great troubles and much strife, and be ofttimes in death-shadowing peril. \"If mine aid you need at any time,\" she said, \"come to my grave chamber and invoke my spirit, and I shall rise to help you.\" Soon after she spake thus Groa died, and Svipdag wept for her.\n\nThen Orvandel took for wife the beauteous Sith. Their son was Ull, and he grew up to be a strong young warrior like his half-brother.\n\nSvipdag was overcome with desire to be avenged upon Halfdan, and sought to wage war against him. But Sith prevailed upon him to promise that he would go towards the mountains of Jotun-heim, and rescue the goddess Freyja and the god Frey from the giant who kept them imprisoned in his strong castle.\n\nBut Svipdag deemed Sith to be moved with cunning intentions, and he feared that if he went forth upon such an enterprise he would never return. He had need of counsel and of help, and in the darkness of night he went to the stone grave-chamber of his mother and called upon her.\n\n\"Awake,\" he cried, \"as thou didst promise me, and come to me, O mother, in my sore straits!\"\n\nThe spirit of Groa rose out of Hela, where she heard her son's voice calling upon her, and from the grave-chamber she spoke. She told him that he must indeed go on a long journey and meet many perils ere yet he would find Freyja, but she bade him remember that his Norn of fate would be his guide.",

					"Then sang she incantations over Svipdag to protect him from danger and to heal his wounds, to give him courage and set him free from prisons. She also sang incantations to protect him against raging rivers he must needs cross, and against ocean's perils and the perils of vast and high mountains over which he must climb.\n\nNine incantations did Groa utter, and the last gave him security to traverse Nifel-hel and enter Mimer's grove.\n\nWhereupon Groa's voice was silent, and her spirit returned to the Underworld.\n\nSatisfied he would be indeed safe from all danger, Svipdag went northward towards the battleground of the giants. It was his desire to first avenge his grandsire's death and his mother's shame ere yet he would search to find Freyja. So he set himself to lead a giant host against the army of Halfdan, and a dread conflict was fought.\n\nSvipdag was in the midst of the battle, and with Halfdan he waged a duel, but he was overcome and taken prisoner. Then made the giants hurried flight towards the north.\n\nDeep was Halfdan's admiration for the prowess of the young hero, and he offered him his friendship if he would become his ally and help him to continue the campaign against the giants with whom Ivalde's sons were in league. But Svipdag scorned his friendship with defiance, and Halfdan in his wrath caused him to be bound to a tree in the midst of a thick forest, so that he might become the prey of wild beasts.\n\nGroa's son, when he was alone, bethought him of the incantations which his mother had uttered, and one he repeated till the chains that bound him flew away and he was set free. Hither and thither he wandered disconsolately,",

					"nor giant nor foeman could he see, nor could he discover which way he should go.\n\nThen came he to the moon-god ere he rose on his path through the heavens, and by him was Svipdag told where he would find the Sword of Victory which Thjasse-Volund had forged.\n\n\"In Mimer's cave,\" the moon-god said, \"it is concealed, and thou must needs overcome the Keeper of Hela's gate to obtain it.\"\n\nTowards the trackless regions that lead by Hvergelmer's mountain did Svipdag then journey, and over the caves in which giants guard their accursed hoards of treasure. Intense and bitter cold prevailed as he traversed over frostbound ways and wreaths of blocking snow. Now he had need to climb great precipices, and ofttimes he found himself on dizzy mountain ridges, while dread chasms yawned below him. Through many places of horror and peril did Svipdag traverse until he reached the borders of Hela. There he beheld a fair land that gleamed before him, full of flowers of rich fragrance.\n\nHe crossed a dark valley, and a hel-hound pursued him, barking loudly. Then came he to the River of Blades, which was spanned by a bridge of gold, and beyond there was a stone door in Hela's wall, guarded by a strong watchman. With him Svipdag fought and was victorious, and he entered the land of spirits where dwells Mimer and the regenerating race unborn.\n\nProtected by the enchantment of Groa, Svipdag went towards the cave in which the treasures of Mimer are concealed, nor did he let his shadow fall upon it lest Mimer's son Mimingus, who kept watch, should take fear and shrink back into the mountain.\n\nMimingus lay asleep, and Svipdag overcame him and",

					"bound him where he lay. He took from the wall the glittering Sword of Victory and the great Arm-ring which Thjasse-Volund had forged, and then hastened to return by the way he had come. So traversing again the mountains of snow and misty blackness, and escaping the dread perils about him, Svipdag returned with his treasures from the Underworld.\n\nThen without delay did the vengeance-seeking son of Groa open a new campaign against Halfdan. In Asgard it was known that he had secured the dreaded sword which Thjasse-Volund had made so that he might overcome the gods. Mighty Thor seized his iron hammer and went forth to help his son.\n\nGreat was the battle which was waged. Svipdag mowed down his enemies before him, and Halfdan was sorely wounded by an arrow shot from the bow of Orvandel-Egil. Then did Thor press into the midst of the fray, fighting fiercely against the giants, who fell before him until he came against Svipdag. But the hammer which Sindre had made was of no avail against, the young hero, for with the Sword of Victory it was struck by The Shining One and severed from the handle.\n\nWhen Thor was repulsed he fled from the field, and Halfdan went with him.\n\nThus did victory come to Svipdag, and thus was the judgment of the gods defied, for they had placed the workmanship of Sindre's kinsman above that of the sons of Ivalde.\n\nHalfdan died of his wounds, and Thor made haste to Asgard, where the gods awaited the coming of Svipdag with the Sword of Victory, which had been forged so that they might be utterly overcome and Asgard laid waste."
				}
			},
			Svipdagsmol = {
				Title = "Svipdagsmol",
				Index = 26,
				Text = {
					"",
				}
			},
		}
	},
	--]]

--Load("scripts/texts/the_ethnology_of_germany.lua")
