--       _________ __                 __
--      /   _____//  |_____________ _/  |______     ____  __ __  ______
--      \_____  \\   __\_  __ \__  \\   __\__  \   / ___\|  |  \/  ___/
--      /        \|  |  |  | \// __ \|  |  / __ \_/ /_/  >  |  /\___ \
--     /_______  /|__|  |__|  (____  /__| (____  /\___  /|____//____  >
--             \/                  \/          \//_____/            \/
--  ______________________                           ______________________
--                        T H E   W A R   B E G I N S
--         Stratagus - A free fantasy real time strategy game engine
--
--      (c) Copyright 2016 by Andrettin
--
--      This program is free software; you can redistribute it and/or modify
--      it under the terms of the GNU General Public License as published by
--      the Free Software Foundation; either version 2 of the License, or
--      (at your option) any later version.
--
--      This program is distributed in the hope that it will be useful,
--      but WITHOUT ANY WARRANTY; without even the implied warranty of
--      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--      GNU General Public License for more details.
--
--      You should have received a copy of the GNU General Public License
--      along with this program; if not, write to the Free Software
--      Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
--

DefineMapTemplate("earth", {
	Name = "Earth",
	World = "Earth",
	Width = 8192,
	Height = 4096,
	TerrainFile = "scripts/map_templates/earth.map",
	GeneratedTerrains = {
		"rock", "medium",
		"grass", "extremely-high",
		"dirt", "high",
		"pine-tree", "high"
	},
	GeneratedNeutralUnits = {
		"unit-gold-deposit", 8,
		"unit-silver-deposit", 8,
		"unit-copper-deposit", 8,
		"unit-bee", 64,
		"unit-fly", 64,
		"unit-bug", 64,
		"unit-worm", 64,
		"unit-snail", 64,
		"unit-slug", 64,
		"unit-frog", 64,
		"unit-bird", 64,
		"unit-crow", 64,
		"unit-rat", 64,
		"unit-goat", 32,
		"unit-boar", 32,
		"unit-horse", 16
	},
	PlayerLocationGeneratedNeutralUnits = {
		"unit-gold-deposit", 1,
		"unit-wood-pile", 16,
		"unit-stone-pile", 8
	}
})

SetMapTemplateTileTerrain("earth", "shallow-water", 4033, 756)
SetMapTemplateTileTerrain("earth", "shallow-water", 4034, 756)
SetMapTemplateTileTerrain("earth", "shallow-water", 4035, 760)
SetMapTemplateTileTerrain("earth", "shallow-water", 4036, 760)
SetMapTemplateTileTerrain("earth", "shallow-water", 4036, 762)
SetMapTemplateTileTerrain("earth", "shallow-water", 4037, 753)
SetMapTemplateTileTerrain("earth", "shallow-water", 4037, 759)
SetMapTemplateTileTerrain("earth", "shallow-water", 4037, 760)
SetMapTemplateTileTerrain("earth", "shallow-water", 4037, 761)
SetMapTemplateTileTerrain("earth", "shallow-water", 4037, 762)
SetMapTemplateTileTerrain("earth", "shallow-water", 4038, 752)
SetMapTemplateTileTerrain("earth", "shallow-water", 4038, 753)
SetMapTemplateTileTerrain("earth", "shallow-water", 4038, 759)
SetMapTemplateTileTerrain("earth", "shallow-water", 4038, 761)
SetMapTemplateTileTerrain("earth", "shallow-water", 4038, 762)
SetMapTemplateTileTerrain("earth", "shallow-water", 4039, 752)
SetMapTemplateTileTerrain("earth", "shallow-water", 4039, 753)
SetMapTemplateTileTerrain("earth", "shallow-water", 4040, 752)
SetMapTemplateTileTerrain("earth", "shallow-water", 4042, 754)
SetMapTemplateTileTerrain("earth", "shallow-water", 4042, 755)
SetMapTemplateTileTerrain("earth", "shallow-water", 4043, 752)
SetMapTemplateTileTerrain("earth", "shallow-water", 4043, 753)
SetMapTemplateTileTerrain("earth", "shallow-water", 4043, 754)
SetMapTemplateTileTerrain("earth", "shallow-water", 4043, 755)
SetMapTemplateTileTerrain("earth", "shallow-water", 4044, 751)
SetMapTemplateTileTerrain("earth", "shallow-water", 4044, 752)
SetMapTemplateTileTerrain("earth", "shallow-water", 4044, 753)
SetMapTemplateTileTerrain("earth", "shallow-water", 4044, 754)
SetMapTemplateTileTerrain("earth", "shallow-water", 4045, 751)
SetMapTemplateTileTerrain("earth", "shallow-water", 4045, 752)
SetMapTemplateTileTerrain("earth", "shallow-water", 4045, 753)
SetMapTemplateTileTerrain("earth", "shallow-water", 4045, 754)
SetMapTemplateTileTerrain("earth", "shallow-water", 4046, 751)
SetMapTemplateTileTerrain("earth", "shallow-water", 4046, 752)
SetMapTemplateTileTerrain("earth", "shallow-water", 4046, 753)
SetMapTemplateTileTerrain("earth", "shallow-water", 4046, 754)
SetMapTemplateTileTerrain("earth", "shallow-water", 4046, 760)
SetMapTemplateTileTerrain("earth", "shallow-water", 4047, 751)
SetMapTemplateTileTerrain("earth", "shallow-water", 4047, 752)
SetMapTemplateTileTerrain("earth", "shallow-water", 4047, 753)
SetMapTemplateTileTerrain("earth", "shallow-water", 4047, 754)
SetMapTemplateTileTerrain("earth", "shallow-water", 4047, 755)
SetMapTemplateTileTerrain("earth", "shallow-water", 4048, 751)
SetMapTemplateTileTerrain("earth", "shallow-water", 4048, 752)
SetMapTemplateTileTerrain("earth", "shallow-water", 4048, 753)
SetMapTemplateTileTerrain("earth", "shallow-water", 4048, 754)
SetMapTemplateTileTerrain("earth", "shallow-water", 4048, 755)
SetMapTemplateTileTerrain("earth", "shallow-water", 4048, 756)
SetMapTemplateTileTerrain("earth", "shallow-water", 4049, 757)
SetMapTemplateTileTerrain("earth", "shallow-water", 4049, 759)
SetMapTemplateTileTerrain("earth", "shallow-water", 4050, 758)
SetMapTemplateTileTerrain("earth", "shallow-water", 4050, 759)
SetMapTemplateTileTerrain("earth", "shallow-water", 4051, 758)
SetMapTemplateTileTerrain("earth", "shallow-water", 4051, 759)

SetMapTemplateTileTerrain("earth", "shallow-water", 4121, 718, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4122, 718, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4123, 718, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4124, 717, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4124, 718, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4125, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4125, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4125, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4125, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4125, 717, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4125, 718, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4126, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4126, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4126, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4126, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4126, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4126, 717, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4127, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4127, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4127, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4127, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4127, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4127, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4128, 717, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4129, 717, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4130, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4131, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4132, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4133, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4134, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4135, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4135, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4135, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4135, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4135, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4135, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4135, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4135, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4135, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4135, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4136, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4136, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4136, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4136, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4136, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4136, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4136, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4136, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4136, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4137, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4137, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4137, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4137, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4137, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4137, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4137, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4137, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4138, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4138, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4138, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4138, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4138, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4138, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4139, 698, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4139, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4139, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4139, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4139, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4139, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4139, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4140, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4141, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 715, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4142, 716, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 697, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 698, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4143, 714, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 697, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 698, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4144, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 698, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4145, 713, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4146, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4147, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4148, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 697, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 698, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4149, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 697, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 698, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4150, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 697, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 698, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4151, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 697, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 698, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 710, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4152, 712, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4153, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 698, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4154, 711, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 698, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4155, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4156, 709, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4157, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4157, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4157, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4157, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4157, 703, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4157, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4157, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4157, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4157, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4157, 708, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4158, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4158, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4158, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4158, 702, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4158, 705, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4158, 706, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4158, 707, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4159, 699, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4159, 700, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4159, 701, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4159, 704, "Lake Wener")
SetMapTemplateTileTerrain("earth", "shallow-water", 4160, 704, "Lake Wener")

SetMapTemplateTileLabel("earth", "The Weald", {3843, 886})

SetMapTemplateResource("earth", "unit-copper-deposit", {3695, 1079}) -- Tin deposits; Source: "Atlas de História Mundial", 2001, p. 41.
SetMapTemplateResource("earth", "unit-copper-deposit", {3727, 902}) -- Tin deposits; Source: "Atlas de História Mundial", 2001, p. 41.
SetMapTemplateResource("earth", "unit-copper-deposit", {3749, 956}) -- Tin deposits; Source: "Ancient Europe 8000 B.C.-A.D. 1000: Encyclopedia of the Barbarian World", 2004, vol. 2, p. 7.
SetMapTemplateResource("earth", "unit-copper-deposit", {4142, 907}) -- Tin deposits; Source: "Atlas de História Mundial", 2001, p. 41.

SetMapTemplateResource("earth", "unit-copper-deposit", {3655, 1192}) -- Iron deposits; Source: http://www.lib.utexas.edu/maps/europe/portugal_econ_1972.jpg
SetMapTemplateResource("earth", "unit-copper-deposit", {3680, 1109}) -- Iron deposits; Source: http://www.lib.utexas.edu/maps/europe/portugal_econ_1972.jpg

SetMapTemplateResource("earth", "unit-copper-deposit", {3675, 1201}) -- Copper deposits; Source: http://www.lib.utexas.edu/maps/europe/spain_mineral_1974.jpg
SetMapTemplateResource("earth", "unit-copper-deposit", {3684, 1195}) -- Copper deposits; Source: http://www.lib.utexas.edu/maps/europe/spain_mineral_1974.jpg
SetMapTemplateResource("earth", "unit-copper-deposit", {3686, 1201}) -- Copper deposits; Source: http://www.lib.utexas.edu/maps/europe/spain_mineral_1974.jpg
SetMapTemplateResource("earth", "unit-copper-deposit", {3687, 1194}) -- Copper deposits; Source: http://www.lib.utexas.edu/maps/europe/spain_mineral_1974.jpg
SetMapTemplateResource("earth", "unit-copper-deposit", {3695, 1201}) -- Copper deposits; Source: http://www.lib.utexas.edu/maps/europe/spain_mineral_1974.jpg
SetMapTemplateResource("earth", "unit-copper-deposit", {3792, 1194}) -- Copper deposits; Source: http://www.lib.utexas.edu/maps/europe/spain_mineral_1974.jpg

SetMapTemplateResource("earth", "unit-gold-deposit", {4169, 913}, 0, "the-wedding-veil") -- gold mine located in Jilova; Source: Alena Ježková, "77 Prague Legends", 2006, p. 31.
SetMapTemplateResource("earth", "unit-silver-deposit", {4194, 927}, 0, "esel") -- silver mine located in Kutná Hora; Source: Alena Ježková, "22 Böhmische Legenden", 2007, pp. 82-83.
SetMapTemplateResource("earth", "unit-silver-deposit", {4194, 928}, 0, "smitna") -- silver mine located in Kutná Hora; moved slightly to the south so that both it and Esel can coexist; Source: Alena Ježková, "22 Böhmische Legenden", 2007, p. 81.

SetMapTemplateUnit("earth", "unit-germanic-town-hall", "Yngling Tribe", {4243, 692}, -2800) -- Sigtun / Segiztûna; in the Ynglinga saga, "Odin's people", the Asa, settle Scandinavia in a manner not too dissimilar from what archaeological findings tell us of Indo-European settlement in the region; thus the name "Asa Tribe" is used here to denote the Indo-European-speaking peoples who settled in Scandinavia, and were the precursors of the Germanic peoples; "Segiztûna" is a rendering of "Sigtun" in Proto-Germanic, since the Ynglinga saga the city was founded when the cultural ancestors of the Germanic peoples (= Odin's people) first settled Scandinavia; the Ynglings were the dynasty founded by Odin's son Yngve, who ruled the Swedish lands

SetMapTemplateUnit("earth", "unit-germanic-town-hall", "Ingaevone Tribe", {4054, 801}, -2800) -- Flensburg; according to Tacitus the Ingaevones were one of the earliest Germanic tribes; the place of their dwelling was inhabited by the cultural ancestors of the Germanics in 2800 BC already

SetMapTemplateUnit("earth", "unit-germanic-town-hall", "Skeldung Tribe", {4112, 784}, -2800) -- Leidre / Lejre; Funnel Beaker culture ended in Zealand in 2800 BC and the Corded Ware culture (neolithic) began; Source: "Ancient Europe 8000 B.C.-A.D. 1000: Encyclopedia of the Barbarian World", 2004, vol. 1, p. 38. In the Ynglinga Saga, Odin set his son Skjöldr to rule in Leidre after their people (who here we equate with the cultural ancestors of the Germanics who migrated to Scandinavia) conquered the land

SetMapTemplateUnit("earth", "unit-latin-town-hall", "Rome", {4126, 1096}, -500) -- Rome had been founded and was independent by 500 BC; Source: William R. Shepherd, "Historical Atlas", 1911, p. 29.

SetMapTemplateLayerConnector("earth", "unit-glyph", {3766, 667 + 70}, "Asgard")

-- In Welsh legends, Gorsedd Arberth (a hill/burial mound near Arberth) was a gateway to Annwn; thus it could be a portal that leads to Annwn in Alfheim; ; Source: Bernhard Maier (trans.), "Das Sagenbuch der Walisischen Kelten", 1999, p. 124.