
SetWorldMapSize(64, 48)

local dark_plains_id = GetWorldMapTerrainTypeId("Dark Plains")
local water_id = GetWorldMapTerrainTypeId("Water")
local hills_id = GetWorldMapTerrainTypeId("Hills")
local mountains_id = GetWorldMapTerrainTypeId("Mountains")
local scrub_forest_id = GetWorldMapTerrainTypeId("Scrub Forest")

SetWorldMapTileTerrain(12, 3, dark_plains_id)
SetWorldMapTileTerrain(12, 4, dark_plains_id)
SetWorldMapTileTerrain(13, 2, dark_plains_id)
SetWorldMapTileTerrain(13, 3, hills_id)
SetWorldMapTileTerrain(13, 4, hills_id)
SetWorldMapTileTerrain(14, 2, hills_id)
SetWorldMapTileTerrain(14, 3, hills_id)
SetWorldMapTileTerrain(14, 4, hills_id)
SetWorldMapTileTerrain(14, 10, dark_plains_id)
SetWorldMapTileTerrain(14, 11, dark_plains_id)
SetWorldMapTileTerrain(15, 1, scrub_forest_id)
AddWorldMapResource("lumber", 15, 1, true)
SetWorldMapTileTerrain(15, 2, hills_id)
SetWorldMapTileTerrain(15, 3, hills_id)
SetWorldMapTileTerrain(15, 4, dark_plains_id)
SetWorldMapTileTerrain(15, 7, dark_plains_id)
SetWorldMapTileTerrain(15, 8, dark_plains_id)
SetWorldMapTileTerrain(15, 9, dark_plains_id)
SetWorldMapTileTerrain(15, 10, dark_plains_id)
SetWorldMapTileTerrain(15, 11, hills_id)
SetWorldMapTileTerrain(15, 12, dark_plains_id)
SetWorldMapTileTerrain(16, 0, dark_plains_id)
SetWorldMapTileTerrain(16, 1, mountains_id)
SetWorldMapTileTerrain(16, 2, hills_id)
SetWorldMapTileTerrain(16, 3, hills_id)
SetWorldMapTileTerrain(16, 4, dark_plains_id)
SetWorldMapTileTerrain(16, 5, dark_plains_id)
SetWorldMapTileTerrain(16, 6, dark_plains_id)
SetWorldMapTileTerrain(16, 7, dark_plains_id)
SetWorldMapTileTerrain(16, 8, hills_id)
SetWorldMapTileTerrain(16, 9, hills_id)
SetWorldMapTileTerrain(16, 10, dark_plains_id)
SetWorldMapTileTerrain(16, 11, hills_id)
SetWorldMapTileTerrain(16, 12, hills_id)
SetWorldMapTileTerrain(17, 0, mountains_id)
SetWorldMapTileTerrain(17, 1, mountains_id)
SetWorldMapTileTerrain(17, 2, hills_id)
SetWorldMapTileTerrain(17, 3, hills_id)
SetWorldMapTileTerrain(17, 4, dark_plains_id)
SetWorldMapTileTerrain(17, 5, dark_plains_id)
SetWorldMapTileTerrain(17, 6, dark_plains_id)
SetWorldMapTileTerrain(17, 7, dark_plains_id)
SetWorldMapTileTerrain(17, 8, hills_id)
SetWorldMapTileTerrain(17, 9, hills_id)
SetWorldMapTileTerrain(17, 10, dark_plains_id)
SetWorldMapTileTerrain(17, 11, hills_id)
SetWorldMapTileTerrain(17, 12, hills_id)
SetWorldMapTileTerrain(17, 13, dark_plains_id)
SetWorldMapTileTerrain(18, 0, mountains_id)
SetWorldMapTileTerrain(18, 1, mountains_id)
SetWorldMapTileTerrain(18, 2, hills_id)
SetWorldMapTileTerrain(18, 3, hills_id)
SetWorldMapTileTerrain(18, 4, dark_plains_id)
SetWorldMapTileTerrain(18, 5, dark_plains_id)
SetWorldMapTileTerrain(18, 6, hills_id)
SetWorldMapTileTerrain(18, 7, dark_plains_id)
SetWorldMapTileTerrain(18, 8, dark_plains_id)
SetWorldMapTileTerrain(18, 9, hills_id)
SetWorldMapTileTerrain(18, 10, hills_id)
SetWorldMapTileTerrain(18, 11, hills_id)
SetWorldMapTileTerrain(18, 12, hills_id)
SetWorldMapTileTerrain(18, 29, dark_plains_id)
SetWorldMapTileTerrain(18, 30, dark_plains_id)
SetWorldMapTileTerrain(19, 0, mountains_id)
SetWorldMapTileTerrain(19, 1, mountains_id)
SetWorldMapTileTerrain(19, 2, hills_id)
SetWorldMapTileTerrain(19, 3, hills_id)
SetWorldMapTileTerrain(19, 4, dark_plains_id)
SetWorldMapTileTerrain(19, 5, hills_id)
SetWorldMapTileTerrain(19, 6, hills_id)
SetWorldMapTileTerrain(19, 7, dark_plains_id)
SetWorldMapTileTerrain(19, 8, hills_id)
SetWorldMapTileTerrain(19, 9, hills_id)
SetWorldMapTileTerrain(19, 10, hills_id)
SetWorldMapTileTerrain(19, 11, hills_id)
SetWorldMapTileTerrain(19, 12, hills_id)
SetWorldMapTileTerrain(19, 13, dark_plains_id)
SetWorldMapTileTerrain(19, 28, dark_plains_id)
SetWorldMapTileTerrain(19, 29, hills_id)
SetWorldMapTileTerrain(19, 30, hills_id)
SetWorldMapTileTerrain(20, 1, hills_id)
SetWorldMapTileTerrain(20, 2, hills_id)
SetWorldMapTileTerrain(20, 3, hills_id)
SetWorldMapTileTerrain(20, 4, hills_id)
SetWorldMapTileTerrain(20, 5, mountains_id)
SetWorldMapTileTerrain(20, 6, hills_id)
SetWorldMapTileTerrain(20, 7, hills_id)
SetWorldMapTileTerrain(20, 8, hills_id)
SetWorldMapTileTerrain(20, 9, hills_id)
SetWorldMapTileTerrain(20, 10, hills_id)
SetWorldMapTileTerrain(20, 11, hills_id)
SetWorldMapTileTerrain(20, 12, hills_id)
SetWorldMapTileTerrain(20, 13, hills_id)
SetWorldMapTileTerrain(20, 28, hills_id)
SetWorldMapTileTerrain(20, 29, hills_id)
SetWorldMapTileTerrain(20, 30, dark_plains_id)
SetWorldMapTileTerrain(20, 31, dark_plains_id)
SetWorldMapTileTerrain(20, 32, dark_plains_id)
SetWorldMapTileTerrain(21, 1, dark_plains_id)
SetWorldMapTileTerrain(21, 2, dark_plains_id)
SetWorldMapTileTerrain(21, 3, dark_plains_id)
SetWorldMapTileTerrain(21, 4, mountains_id)
SetWorldMapTileTerrain(21, 5, mountains_id)
SetWorldMapTileTerrain(21, 6, mountains_id)
SetWorldMapTileTerrain(21, 7, mountains_id)
SetWorldMapTileTerrain(21, 8, hills_id)
SetWorldMapTileTerrain(21, 9, mountains_id)
SetWorldMapTileTerrain(21, 10, mountains_id)
SetWorldMapTileTerrain(21, 11, mountains_id)
SetWorldMapTileTerrain(21, 12, hills_id)
SetWorldMapTileTerrain(21, 13, hills_id)
SetWorldMapTileTerrain(21, 28, hills_id)
SetWorldMapTileTerrain(21, 29, hills_id)
SetWorldMapTileTerrain(21, 30, hills_id)
SetWorldMapTileTerrain(21, 31, hills_id)
SetWorldMapTileTerrain(21, 32, dark_plains_id)
SetWorldMapTileTerrain(22, 0, hills_id)
SetWorldMapTileTerrain(22, 1, mountains_id)
SetWorldMapTileTerrain(22, 2, mountains_id)
SetWorldMapTileTerrain(22, 3, dark_plains_id)
SetWorldMapTileTerrain(22, 4, mountains_id)
SetWorldMapTileTerrain(22, 5, mountains_id)
SetWorldMapTileTerrain(22, 6, mountains_id)
SetWorldMapTileTerrain(22, 7, mountains_id)
SetWorldMapTileTerrain(22, 8, mountains_id)
SetWorldMapTileTerrain(22, 9, mountains_id)
SetWorldMapTileTerrain(22, 10, mountains_id)
SetWorldMapTileTerrain(22, 11, mountains_id)
SetWorldMapTileTerrain(22, 12, mountains_id)
SetWorldMapTileTerrain(22, 13, hills_id)
SetWorldMapTileTerrain(22, 25, dark_plains_id)
SetWorldMapTileTerrain(22, 26, dark_plains_id)
SetWorldMapTileTerrain(22, 27, dark_plains_id)
SetWorldMapTileTerrain(22, 28, dark_plains_id)
SetWorldMapTileTerrain(22, 29, hills_id)
AddWorldMapResource("gold", 22, 29, true) -- location of the Troll Hole in the Brown Hills
SetWorldMapTileTerrain(22, 30, hills_id)
SetWorldMapTileTerrain(22, 31, hills_id)
SetWorldMapTileTerrain(22, 32, dark_plains_id)
SetWorldMapTileTerrain(23, 0, hills_id)
SetWorldMapTileTerrain(23, 1, mountains_id)
SetWorldMapTileTerrain(23, 2, mountains_id)
SetWorldMapTileTerrain(23, 3, mountains_id)
SetWorldMapTileTerrain(23, 4, mountains_id)
SetWorldMapTileTerrain(23, 5, hills_id)
SetWorldMapTileTerrain(23, 6, mountains_id)
SetWorldMapTileTerrain(23, 7, mountains_id)
SetWorldMapTileTerrain(23, 8, mountains_id)
SetWorldMapTileTerrain(23, 9, mountains_id)
SetWorldMapTileTerrain(23, 10, mountains_id)
SetWorldMapTileTerrain(23, 11, mountains_id)
SetWorldMapTileTerrain(23, 12, mountains_id)
SetWorldMapTileTerrain(23, 13, hills_id)
SetWorldMapTileTerrain(23, 25, hills_id)
SetWorldMapTileTerrain(23, 26, hills_id)
SetWorldMapTileTerrain(23, 27, hills_id)
SetWorldMapTileTerrain(23, 28, dark_plains_id)
SetWorldMapTileTerrain(23, 29, hills_id)
SetWorldMapTileTerrain(23, 30, hills_id)
SetWorldMapTileTerrain(23, 31, hills_id)
SetWorldMapTileTerrain(23, 32, hills_id)
SetWorldMapTileTerrain(24, 0, mountains_id)
SetWorldMapTileTerrain(24, 1, mountains_id)
SetWorldMapTileTerrain(24, 2, mountains_id)
SetWorldMapTileTerrain(24, 3, mountains_id)
SetWorldMapTileTerrain(24, 4, mountains_id)
SetWorldMapTileTerrain(24, 5, hills_id)
SetWorldMapTileTerrain(24, 6, hills_id)
SetWorldMapTileTerrain(24, 7, mountains_id)
SetWorldMapTileTerrain(24, 8, mountains_id)
SetWorldMapTileTerrain(24, 9, mountains_id)
SetWorldMapTileTerrain(24, 10, mountains_id)
SetWorldMapTileTerrain(24, 11, mountains_id)
SetWorldMapTileTerrain(24, 12, mountains_id)
SetWorldMapTileTerrain(24, 13, mountains_id)
SetWorldMapTileTerrain(24, 14, hills_id)
SetWorldMapTileTerrain(24, 22, dark_plains_id)
SetWorldMapTileTerrain(24, 24, dark_plains_id)
SetWorldMapTileTerrain(24, 25, hills_id)
SetWorldMapTileTerrain(24, 26, hills_id)
SetWorldMapTileTerrain(24, 27, hills_id)
SetWorldMapTileTerrain(24, 28, dark_plains_id)
SetWorldMapTileTerrain(24, 29, dark_plains_id)
SetWorldMapTileTerrain(24, 30, hills_id)
SetWorldMapTileTerrain(24, 31, hills_id)
SetWorldMapTileTerrain(24, 32, hills_id)
SetWorldMapTileTerrain(25, 0, hills_id)
SetWorldMapTileTerrain(25, 1, mountains_id)
SetWorldMapTileTerrain(25, 2, mountains_id)
SetWorldMapTileTerrain(25, 3, hills_id)
SetWorldMapTileTerrain(25, 4, hills_id)
SetWorldMapTileTerrain(25, 5, hills_id)
SetWorldMapTileTerrain(25, 6, hills_id)
SetWorldMapTileTerrain(25, 7, mountains_id)
SetWorldMapTileTerrain(25, 8, mountains_id)
SetWorldMapTileTerrain(25, 9, mountains_id)
SetWorldMapTileTerrain(25, 10, mountains_id)
SetWorldMapTileTerrain(25, 11, mountains_id)
SetWorldMapTileTerrain(25, 12, mountains_id)
SetWorldMapTileTerrain(25, 13, mountains_id)
SetWorldMapTileTerrain(25, 14, hills_id)
SetWorldMapTileTerrain(25, 15, hills_id)
SetWorldMapTileTerrain(25, 16, dark_plains_id)
SetWorldMapTileTerrain(25, 20, hills_id)
SetWorldMapTileTerrain(25, 21, dark_plains_id)
SetWorldMapTileTerrain(25, 22, dark_plains_id)
SetWorldMapTileTerrain(25, 23, dark_plains_id)
SetWorldMapTileTerrain(25, 24, hills_id)
SetWorldMapTileTerrain(25, 25, hills_id)
SetWorldMapTileTerrain(25, 26, dark_plains_id)
SetWorldMapTileTerrain(25, 27, hills_id)
SetWorldMapTileTerrain(25, 28, dark_plains_id)
SetWorldMapTileTerrain(25, 29, dark_plains_id)
SetWorldMapTileTerrain(25, 30, hills_id)
SetWorldMapTileTerrain(25, 31, hills_id)
SetWorldMapTileTerrain(25, 32, dark_plains_id)
SetWorldMapTileTerrain(26, 0, hills_id)
SetWorldMapTileTerrain(26, 1, mountains_id)
SetWorldMapTileTerrain(26, 2, mountains_id)
SetWorldMapTileTerrain(26, 3, mountains_id)
SetWorldMapTileTerrain(26, 4, hills_id)
SetWorldMapTileTerrain(26, 5, hills_id)
SetWorldMapTileTerrain(26, 6, dark_plains_id)
SetWorldMapTileTerrain(26, 7, dark_plains_id)
SetWorldMapTileTerrain(26, 8, mountains_id)
SetWorldMapTileTerrain(26, 9, mountains_id)
SetWorldMapTileTerrain(26, 10, mountains_id)
SetWorldMapTileTerrain(26, 11, mountains_id)
SetWorldMapTileTerrain(26, 12, mountains_id)
SetWorldMapTileTerrain(26, 13, mountains_id)
SetWorldMapTileTerrain(26, 14, hills_id)
SetWorldMapTileTerrain(26, 15, hills_id)
SetWorldMapTileTerrain(26, 20, hills_id)
SetWorldMapTileTerrain(26, 21, hills_id)
SetWorldMapTileTerrain(26, 22, dark_plains_id)
SetWorldMapTileTerrain(26, 23, hills_id)
SetWorldMapTileTerrain(26, 24, hills_id)
SetWorldMapTileTerrain(26, 25, hills_id)
SetWorldMapTileTerrain(26, 26, hills_id)
SetWorldMapTileTerrain(26, 27, hills_id)
SetWorldMapTileTerrain(26, 28, hills_id)
SetWorldMapTileTerrain(26, 29, dark_plains_id)
SetWorldMapTileTerrain(26, 30, hills_id)
SetWorldMapTileTerrain(26, 31, dark_plains_id)
SetWorldMapTileTerrain(27, 0, hills_id)
SetWorldMapTileTerrain(27, 1, mountains_id)
SetWorldMapTileTerrain(27, 2, mountains_id)
SetWorldMapTileTerrain(27, 3, hills_id)
SetWorldMapTileTerrain(27, 4, hills_id)
SetWorldMapTileTerrain(27, 5, dark_plains_id)
SetWorldMapTileTerrain(27, 6, water_id)
SetWorldMapTileTerrain(27, 7, water_id)
SetWorldMapTileTerrain(27, 8, water_id)
SetWorldMapTileTerrain(27, 9, mountains_id)
SetWorldMapTileTerrain(27, 10, mountains_id)
SetWorldMapTileTerrain(27, 11, mountains_id)
SetWorldMapTileTerrain(27, 12, mountains_id)
SetWorldMapTileTerrain(27, 13, mountains_id)
SetWorldMapTileTerrain(27, 14, hills_id)
SetWorldMapTileTerrain(27, 15, hills_id)
SetWorldMapTileTerrain(27, 16, hills_id)
SetWorldMapTileTerrain(27, 20, dark_plains_id)
SetWorldMapTileTerrain(27, 21, hills_id)
SetWorldMapTileTerrain(27, 22, hills_id)
SetWorldMapTileTerrain(27, 23, hills_id)
SetWorldMapTileTerrain(27, 24, hills_id)
SetWorldMapTileTerrain(27, 25, hills_id)
SetWorldMapTileTerrain(27, 26, hills_id)
SetWorldMapTileTerrain(27, 27, dark_plains_id)
SetWorldMapTileTerrain(27, 28, hills_id)
SetWorldMapTileTerrain(27, 29, dark_plains_id)
SetWorldMapTileTerrain(27, 30, dark_plains_id)
SetWorldMapTileTerrain(28, 0, mountains_id)
SetWorldMapTileTerrain(28, 1, mountains_id)
SetWorldMapTileTerrain(28, 2, mountains_id)
SetWorldMapTileTerrain(28, 3, hills_id)
SetWorldMapTileTerrain(28, 4, hills_id)
SetWorldMapTileTerrain(28, 5, water_id)
SetWorldMapTileTerrain(28, 6, water_id)
SetWorldMapTileTerrain(28, 7, water_id)
SetWorldMapTileTerrain(28, 8, water_id)
SetWorldMapTileTerrain(28, 9, dark_plains_id)
SetWorldMapTileTerrain(28, 10, mountains_id)
SetWorldMapTileTerrain(28, 11, mountains_id)
SetWorldMapTileTerrain(28, 12, mountains_id)
SetWorldMapTileTerrain(28, 13, mountains_id)
SetWorldMapTileTerrain(28, 14, hills_id)
SetWorldMapTileTerrain(28, 15, hills_id)
SetWorldMapTileTerrain(28, 16, hills_id)
SetWorldMapTileTerrain(28, 17, dark_plains_id)
SetWorldMapTileTerrain(28, 20, dark_plains_id)
SetWorldMapTileTerrain(28, 21, dark_plains_id)
SetWorldMapTileTerrain(28, 22, hills_id)
SetWorldMapTileTerrain(28, 23, mountains_id)
SetWorldMapTileTerrain(28, 24, mountains_id)
SetWorldMapTileTerrain(28, 25, hills_id)
SetWorldMapTileTerrain(28, 26, hills_id)
SetWorldMapTileTerrain(28, 27, dark_plains_id)
SetWorldMapTileTerrain(28, 28, hills_id)
SetWorldMapTileTerrain(29, 0, mountains_id)
SetWorldMapTileTerrain(29, 1, mountains_id)
SetWorldMapTileTerrain(29, 2, mountains_id)
SetWorldMapTileTerrain(29, 3, hills_id)
SetWorldMapTileTerrain(29, 4, dark_plains_id)
SetWorldMapTileTerrain(29, 5, water_id)
SetWorldMapTileTerrain(29, 6, water_id)
SetWorldMapTileTerrain(29, 7, water_id)
SetWorldMapTileTerrain(29, 8, water_id)
SetWorldMapTileTerrain(29, 9, mountains_id)
SetWorldMapTileTerrain(29, 10, mountains_id)
SetWorldMapTileTerrain(29, 11, mountains_id)
SetWorldMapTileTerrain(29, 12, mountains_id)
SetWorldMapTileTerrain(29, 13, mountains_id)
SetWorldMapTileTerrain(29, 14, hills_id)
SetWorldMapTileTerrain(29, 15, hills_id)
SetWorldMapTileTerrain(29, 16, hills_id)
SetWorldMapTileTerrain(29, 17, dark_plains_id)
SetWorldMapTileTerrain(29, 18, dark_plains_id)
SetWorldMapTileTerrain(29, 19, dark_plains_id)
SetWorldMapTileTerrain(29, 20, dark_plains_id)
SetWorldMapTileTerrain(29, 21, dark_plains_id)
SetWorldMapTileTerrain(29, 22, scrub_forest_id)
AddWorldMapResource("lumber", 29, 22, true)
SetWorldMapTileTerrain(29, 23, mountains_id)
SetWorldMapTileTerrain(29, 24, mountains_id)
SetWorldMapTileTerrain(29, 25, hills_id)
SetWorldMapTileTerrain(29, 26, hills_id)
SetWorldMapTileTerrain(29, 27, dark_plains_id)
SetWorldMapTileTerrain(29, 28, dark_plains_id)
SetWorldMapTileTerrain(30, 0, mountains_id)
SetWorldMapTileTerrain(30, 1, mountains_id)
SetWorldMapTileTerrain(30, 2, mountains_id)
SetWorldMapTileTerrain(30, 3, hills_id)
SetWorldMapTileTerrain(30, 4, dark_plains_id)
SetWorldMapTileTerrain(30, 5, water_id)
SetWorldMapTileTerrain(30, 6, water_id)
SetWorldMapTileTerrain(30, 7, water_id)
SetWorldMapTileTerrain(30, 8, dark_plains_id)
SetWorldMapTileTerrain(30, 9, mountains_id)
SetWorldMapTileTerrain(30, 10, mountains_id)
SetWorldMapTileTerrain(30, 11, mountains_id)
SetWorldMapTileTerrain(30, 12, mountains_id)
AddWorldMapResource("gold", 30, 12, false)
SetWorldMapTileTerrain(30, 13, mountains_id)
SetWorldMapTileTerrain(30, 14, hills_id)
SetWorldMapTileTerrain(30, 15, hills_id)
SetWorldMapTileTerrain(30, 16, hills_id)
SetWorldMapTileTerrain(30, 17, scrub_forest_id)
AddWorldMapResource("lumber", 30, 17, true)
SetWorldMapTileTerrain(30, 18, dark_plains_id)
SetWorldMapTileTerrain(30, 19, dark_plains_id)
SetWorldMapTileTerrain(30, 20, dark_plains_id)
SetWorldMapTileTerrain(30, 21, dark_plains_id)
SetWorldMapTileTerrain(30, 23, hills_id)
SetWorldMapTileTerrain(30, 24, hills_id)
SetWorldMapTileTerrain(30, 25, hills_id)
SetWorldMapTileTerrain(30, 26, dark_plains_id)
SetWorldMapTileTerrain(30, 27, dark_plains_id)
SetWorldMapTileTerrain(31, 0, mountains_id)
SetWorldMapTileTerrain(31, 1, mountains_id)
SetWorldMapTileTerrain(31, 2, mountains_id)
SetWorldMapTileTerrain(31, 3, hills_id)
SetWorldMapTileTerrain(31, 4, hills_id)
SetWorldMapTileTerrain(31, 5, dark_plains_id)
SetWorldMapTileTerrain(31, 6, dark_plains_id)
SetWorldMapTileTerrain(31, 7, water_id)
SetWorldMapTileTerrain(31, 8, dark_plains_id)
SetWorldMapTileTerrain(31, 9, mountains_id)
SetWorldMapTileTerrain(31, 10, mountains_id)
SetWorldMapTileTerrain(31, 11, mountains_id)
SetWorldMapTileTerrain(31, 12, mountains_id)
SetWorldMapTileTerrain(31, 13, mountains_id)
SetWorldMapTileTerrain(31, 14, hills_id)
AddWorldMapResource("mushrooms", 31, 14, true) -- there was a mushroom farm in the Southern Tunnels (Northern Rebirth: Infested Caves)
SetWorldMapTileTerrain(31, 15, hills_id)
SetWorldMapTileTerrain(31, 16, hills_id)
SetWorldMapTileTerrain(31, 17, dark_plains_id)
SetWorldMapTileTerrain(31, 18, dark_plains_id)
SetWorldMapTileTerrain(31, 19, dark_plains_id)
SetWorldMapTileTerrain(31, 23, dark_plains_id)
SetWorldMapTileTerrain(31, 24, hills_id)
SetWorldMapTileTerrain(31, 25, dark_plains_id)
SetWorldMapTileTerrain(31, 26, dark_plains_id)
SetWorldMapTileTerrain(32, 0, mountains_id)
SetWorldMapTileTerrain(32, 1, mountains_id)
SetWorldMapTileTerrain(32, 2, mountains_id)
SetWorldMapTileTerrain(32, 3, mountains_id)
SetWorldMapTileTerrain(32, 4, hills_id)
SetWorldMapTileTerrain(32, 5, dark_plains_id)
SetWorldMapTileTerrain(32, 6, dark_plains_id)
SetWorldMapTileTerrain(32, 7, dark_plains_id)
SetWorldMapTileTerrain(32, 8, dark_plains_id)
SetWorldMapTileTerrain(32, 9, mountains_id)
SetWorldMapTileTerrain(32, 10, mountains_id)
SetWorldMapTileTerrain(32, 11, mountains_id)
SetWorldMapTileTerrain(32, 12, mountains_id)
SetWorldMapTileTerrain(32, 13, mountains_id)
AddWorldMapResource("gold", 32, 13, false)
SetWorldMapTileTerrain(32, 14, hills_id)
SetWorldMapTileTerrain(32, 15, hills_id)
SetWorldMapTileTerrain(32, 16, hills_id)
SetWorldMapTileTerrain(32, 17, dark_plains_id)
SetWorldMapTileTerrain(32, 18, dark_plains_id)
SetWorldMapTileTerrain(32, 19, dark_plains_id)
SetWorldMapTileTerrain(32, 23, dark_plains_id)
SetWorldMapTileTerrain(32, 24, dark_plains_id)
SetWorldMapTileTerrain(33, 0, mountains_id)
SetWorldMapTileTerrain(33, 1, mountains_id)
SetWorldMapTileTerrain(33, 2, mountains_id)
SetWorldMapTileTerrain(33, 3, mountains_id)
SetWorldMapTileTerrain(33, 4, dark_plains_id)
SetWorldMapTileTerrain(33, 5, dark_plains_id)
SetWorldMapTileTerrain(33, 6, dark_plains_id)
SetWorldMapTileTerrain(33, 7, dark_plains_id)
SetWorldMapTileTerrain(33, 8, dark_plains_id)
SetWorldMapTileTerrain(33, 9, dark_plains_id)
SetWorldMapTileTerrain(33, 10, mountains_id)
SetWorldMapTileTerrain(33, 11, mountains_id)
SetWorldMapTileTerrain(33, 12, mountains_id)
SetWorldMapTileTerrain(33, 13, mountains_id)
SetWorldMapTileTerrain(33, 14, hills_id)
SetWorldMapTileTerrain(33, 15, hills_id)
SetWorldMapTileTerrain(33, 16, hills_id)
SetWorldMapTileTerrain(33, 17, dark_plains_id)
SetWorldMapTileTerrain(33, 18, dark_plains_id)
SetWorldMapTileTerrain(33, 19, dark_plains_id)
SetWorldMapTileTerrain(34, 0, mountains_id)
SetWorldMapTileTerrain(34, 1, mountains_id)
SetWorldMapTileTerrain(34, 2, mountains_id)
SetWorldMapTileTerrain(34, 3, mountains_id)
SetWorldMapTileTerrain(34, 4, hills_id)
SetWorldMapTileTerrain(34, 5, dark_plains_id)
SetWorldMapTileTerrain(34, 6, dark_plains_id)
SetWorldMapTileTerrain(34, 7, dark_plains_id)
SetWorldMapTileTerrain(34, 8, dark_plains_id)
SetWorldMapTileTerrain(34, 9, mountains_id)
SetWorldMapTileTerrain(34, 10, mountains_id)
SetWorldMapTileTerrain(34, 11, mountains_id)
SetWorldMapTileTerrain(34, 12, mountains_id)
SetWorldMapTileTerrain(34, 13, mountains_id)
SetWorldMapTileTerrain(34, 14, hills_id)
AddWorldMapResource("gold", 34, 14, false)
SetWorldMapTileTerrain(34, 15, dark_plains_id)
SetWorldMapTileTerrain(34, 16, dark_plains_id)
SetWorldMapTileTerrain(34, 17, dark_plains_id)
SetWorldMapTileTerrain(35, 0, mountains_id)
SetWorldMapTileTerrain(35, 1, mountains_id)
SetWorldMapTileTerrain(35, 2, mountains_id)
SetWorldMapTileTerrain(35, 3, mountains_id)
SetWorldMapTileTerrain(35, 4, hills_id)
SetWorldMapTileTerrain(35, 5, hills_id)
SetWorldMapTileTerrain(35, 6, dark_plains_id)
SetWorldMapTileTerrain(35, 7, dark_plains_id)
SetWorldMapTileTerrain(35, 8, dark_plains_id)
SetWorldMapTileTerrain(35, 9, dark_plains_id)
SetWorldMapTileTerrain(35, 10, mountains_id)
AddWorldMapResource("gold", 35, 10, false)
SetWorldMapTileTerrain(35, 11, mountains_id)
SetWorldMapTileTerrain(35, 12, mountains_id)
SetWorldMapTileTerrain(35, 13, mountains_id)
SetWorldMapTileTerrain(35, 14, hills_id)
SetWorldMapTileTerrain(35, 15, dark_plains_id)
SetWorldMapTileTerrain(36, 0, mountains_id)
SetWorldMapTileTerrain(36, 1, mountains_id)
SetWorldMapTileTerrain(36, 2, mountains_id)
SetWorldMapTileTerrain(36, 3, mountains_id)
SetWorldMapTileTerrain(36, 4, mountains_id)
SetWorldMapTileTerrain(36, 5, hills_id)
SetWorldMapTileTerrain(36, 6, hills_id)
SetWorldMapTileTerrain(36, 7, dark_plains_id)
SetWorldMapTileTerrain(36, 8, dark_plains_id)
SetWorldMapTileTerrain(36, 9, dark_plains_id)
SetWorldMapTileTerrain(36, 10, mountains_id)
SetWorldMapTileTerrain(36, 11, mountains_id)
SetWorldMapTileTerrain(36, 12, mountains_id)
SetWorldMapTileTerrain(36, 13, hills_id)
SetWorldMapTileTerrain(36, 14, hills_id)
SetWorldMapTileTerrain(36, 15, dark_plains_id)
SetWorldMapTileTerrain(37, 0, mountains_id)
SetWorldMapTileTerrain(37, 1, mountains_id)
SetWorldMapTileTerrain(37, 2, mountains_id)
SetWorldMapTileTerrain(37, 3, mountains_id)
SetWorldMapTileTerrain(37, 4, mountains_id)
SetWorldMapTileTerrain(37, 5, hills_id)
SetWorldMapTileTerrain(37, 6, hills_id)
SetWorldMapTileTerrain(37, 7, hills_id)
SetWorldMapTileTerrain(37, 8, dark_plains_id)
SetWorldMapTileTerrain(37, 9, dark_plains_id)
SetWorldMapTileTerrain(37, 10, dark_plains_id)
SetWorldMapTileTerrain(37, 11, mountains_id)
SetWorldMapTileTerrain(37, 12, hills_id)
SetWorldMapTileTerrain(37, 13, hills_id)
SetWorldMapTileTerrain(37, 14, hills_id)
SetWorldMapTileTerrain(37, 15, dark_plains_id)
SetWorldMapTileTerrain(38, 0, mountains_id)
SetWorldMapTileTerrain(38, 1, mountains_id)
SetWorldMapTileTerrain(38, 2, mountains_id)
SetWorldMapTileTerrain(38, 3, mountains_id)
SetWorldMapTileTerrain(38, 4, mountains_id)
SetWorldMapTileTerrain(38, 5, hills_id)
SetWorldMapTileTerrain(38, 6, hills_id)
SetWorldMapTileTerrain(38, 7, hills_id)
SetWorldMapTileTerrain(38, 8, dark_plains_id)
SetWorldMapTileTerrain(38, 9, dark_plains_id)
SetWorldMapTileTerrain(38, 10, dark_plains_id)
SetWorldMapTileTerrain(38, 11, hills_id)
SetWorldMapTileTerrain(38, 12, hills_id)
SetWorldMapTileTerrain(38, 13, hills_id)
SetWorldMapTileTerrain(38, 14, hills_id)
SetWorldMapTileTerrain(39, 0, mountains_id)
SetWorldMapTileTerrain(39, 1, mountains_id)
SetWorldMapTileTerrain(39, 2, mountains_id)
SetWorldMapTileTerrain(39, 3, mountains_id)
SetWorldMapTileTerrain(39, 4, mountains_id)
SetWorldMapTileTerrain(39, 5, mountains_id)
SetWorldMapTileTerrain(39, 6, hills_id)
AddWorldMapResource("gold", 39, 6, false)
SetWorldMapTileTerrain(39, 7, hills_id)
SetWorldMapTileTerrain(39, 8, hills_id)
SetWorldMapTileTerrain(39, 9, dark_plains_id)
SetWorldMapTileTerrain(39, 10, dark_plains_id)
SetWorldMapTileTerrain(39, 11, hills_id)
SetWorldMapTileTerrain(39, 12, hills_id)
SetWorldMapTileTerrain(39, 13, dark_plains_id)
SetWorldMapTileTerrain(39, 14, dark_plains_id)
SetWorldMapTileTerrain(40, 0, mountains_id)
SetWorldMapTileTerrain(40, 1, mountains_id)
SetWorldMapTileTerrain(40, 2, mountains_id)
SetWorldMapTileTerrain(40, 3, mountains_id)
SetWorldMapTileTerrain(40, 4, mountains_id)
SetWorldMapTileTerrain(40, 5, mountains_id)
SetWorldMapTileTerrain(40, 6, hills_id)
SetWorldMapTileTerrain(40, 7, hills_id)
SetWorldMapTileTerrain(40, 8, dark_plains_id)
SetWorldMapTileTerrain(40, 9, dark_plains_id)
SetWorldMapTileTerrain(40, 10, dark_plains_id)
SetWorldMapTileTerrain(40, 11, hills_id)
SetWorldMapTileTerrain(40, 12, hills_id)
SetWorldMapTileTerrain(40, 13, dark_plains_id)
SetWorldMapTileTerrain(40, 14, hills_id)
SetWorldMapTileTerrain(41, 0, mountains_id)
SetWorldMapTileTerrain(41, 1, mountains_id)
SetWorldMapTileTerrain(41, 2, mountains_id)
SetWorldMapTileTerrain(41, 3, mountains_id)
SetWorldMapTileTerrain(41, 4, mountains_id)
SetWorldMapTileTerrain(41, 5, mountains_id)
SetWorldMapTileTerrain(41, 6, hills_id)
SetWorldMapTileTerrain(41, 7, hills_id)
SetWorldMapTileTerrain(41, 8, hills_id)
SetWorldMapTileTerrain(41, 9, dark_plains_id)
SetWorldMapTileTerrain(41, 10, dark_plains_id)
SetWorldMapTileTerrain(41, 11, hills_id)
SetWorldMapTileTerrain(41, 12, hills_id)
SetWorldMapTileTerrain(41, 13, hills_id)
SetWorldMapTileTerrain(41, 14, dark_plains_id)
SetWorldMapTileTerrain(42, 0, hills_id)
SetWorldMapTileTerrain(42, 1, mountains_id)
SetWorldMapTileTerrain(42, 2, mountains_id)
SetWorldMapTileTerrain(42, 3, mountains_id)
SetWorldMapTileTerrain(42, 4, mountains_id)
SetWorldMapTileTerrain(42, 5, mountains_id)
SetWorldMapTileTerrain(42, 6, hills_id)
SetWorldMapTileTerrain(42, 7, hills_id)
SetWorldMapTileTerrain(42, 8, scrub_forest_id)
AddWorldMapResource("lumber", 42, 8, true)
SetWorldMapTileTerrain(42, 9, dark_plains_id)
SetWorldMapTileTerrain(42, 10, dark_plains_id)
SetWorldMapTileTerrain(42, 11, hills_id)
SetWorldMapTileTerrain(42, 12, hills_id)
SetWorldMapTileTerrain(42, 13, hills_id)
SetWorldMapTileTerrain(42, 14, dark_plains_id)
SetWorldMapTileTerrain(43, 0, hills_id)
SetWorldMapTileTerrain(43, 1, dark_plains_id)
SetWorldMapTileTerrain(43, 2, hills_id)
SetWorldMapTileTerrain(43, 3, mountains_id)
SetWorldMapTileTerrain(43, 4, mountains_id)
SetWorldMapTileTerrain(43, 5, mountains_id)
SetWorldMapTileTerrain(43, 6, hills_id)
SetWorldMapTileTerrain(43, 7, dark_plains_id)
SetWorldMapTileTerrain(43, 8, dark_plains_id)
SetWorldMapTileTerrain(43, 9, dark_plains_id)
SetWorldMapTileTerrain(43, 10, dark_plains_id)
SetWorldMapTileTerrain(43, 11, hills_id)
SetWorldMapTileTerrain(43, 12, hills_id)
SetWorldMapTileTerrain(43, 13, hills_id)
SetWorldMapTileTerrain(43, 14, hills_id)
SetWorldMapTileTerrain(44, 0, water_id)
SetWorldMapTileTerrain(44, 1, water_id)
SetWorldMapTileTerrain(44, 2, mountains_id)
SetWorldMapTileTerrain(44, 3, mountains_id)
SetWorldMapTileTerrain(44, 4, mountains_id)
SetWorldMapTileTerrain(44, 5, mountains_id)
SetWorldMapTileTerrain(44, 6, scrub_forest_id)
AddWorldMapResource("lumber", 44, 6, true)
SetWorldMapTileTerrain(44, 7, dark_plains_id)
SetWorldMapTileTerrain(44, 8, dark_plains_id)
SetWorldMapTileTerrain(44, 9, hills_id)
SetWorldMapTileTerrain(44, 10, hills_id)
SetWorldMapTileTerrain(44, 11, hills_id)
SetWorldMapTileCulturalName(44, 11, "dwarf", "Svarinshaug");
SetWorldMapTileTerrain(44, 12, hills_id)
SetWorldMapTileTerrain(44, 13, hills_id)
SetWorldMapTileTerrain(44, 14, hills_id)
SetWorldMapTileTerrain(45, 0, water_id)
SetWorldMapTileTerrain(45, 1, water_id)
SetWorldMapTileTerrain(45, 2, mountains_id)
SetWorldMapTileTerrain(45, 3, mountains_id)
SetWorldMapTileTerrain(45, 4, mountains_id)
SetWorldMapTileTerrain(45, 5, mountains_id)
SetWorldMapTileTerrain(45, 6, dark_plains_id)
SetWorldMapTileTerrain(45, 7, dark_plains_id)
SetWorldMapTileTerrain(45, 8, dark_plains_id)
SetWorldMapTileTerrain(45, 9, hills_id)
SetWorldMapTileTerrain(45, 10, hills_id)
SetWorldMapTileTerrain(45, 11, hills_id)
SetWorldMapTileTerrain(45, 12, hills_id)
SetWorldMapTileTerrain(45, 13, hills_id)
SetWorldMapTileTerrain(45, 14, hills_id)
SetWorldMapTileTerrain(46, 0, water_id)
SetWorldMapTileTerrain(46, 1, water_id)
SetWorldMapTileTerrain(46, 2, mountains_id)
SetWorldMapTileTerrain(46, 3, mountains_id)
SetWorldMapTileTerrain(46, 4, mountains_id)
SetWorldMapTileTerrain(46, 5, hills_id)
AddWorldMapResource("gold", 46, 5, false)
SetWorldMapTileTerrain(46, 6, dark_plains_id)
SetWorldMapTileTerrain(46, 7, dark_plains_id)
SetWorldMapTileTerrain(46, 8, dark_plains_id)
SetWorldMapTileTerrain(46, 9, dark_plains_id)
SetWorldMapTileTerrain(46, 10, hills_id)
SetWorldMapTileTerrain(46, 11, hills_id)
SetWorldMapTileTerrain(46, 12, hills_id)
SetWorldMapTileTerrain(46, 13, dark_plains_id)
SetWorldMapTileTerrain(46, 14, dark_plains_id)
SetWorldMapTileTerrain(47, 0, water_id)
SetWorldMapTileTerrain(47, 1, dark_plains_id)
SetWorldMapTileTerrain(47, 2, hills_id)
SetWorldMapTileTerrain(47, 3, mountains_id)
SetWorldMapTileTerrain(47, 4, mountains_id)
SetWorldMapTileTerrain(47, 5, mountains_id)
SetWorldMapTileTerrain(47, 6, hills_id)
SetWorldMapTileTerrain(47, 7, dark_plains_id)
SetWorldMapTileTerrain(47, 8, dark_plains_id)
SetWorldMapTileTerrain(47, 9, dark_plains_id)
SetWorldMapTileTerrain(47, 10, hills_id)
SetWorldMapTileTerrain(47, 11, hills_id)
AddWorldMapResource("gold", 47, 11, true) -- to give the Modsogning clan a proper start
SetWorldMapTileTerrain(47, 12, hills_id)
SetWorldMapTileTerrain(47, 13, hills_id)
SetWorldMapTileTerrain(47, 14, dark_plains_id)
SetWorldMapTileTerrain(47, 15, dark_plains_id)
SetWorldMapTileTerrain(47, 16, dark_plains_id)
SetWorldMapTileTerrain(48, 0, dark_plains_id)
SetWorldMapTileTerrain(48, 1, dark_plains_id)
SetWorldMapTileTerrain(48, 2, hills_id)
SetWorldMapTileTerrain(48, 3, mountains_id)
SetWorldMapTileTerrain(48, 4, mountains_id)
SetWorldMapTileTerrain(48, 5, mountains_id)
SetWorldMapTileTerrain(48, 6, hills_id)
SetWorldMapTileTerrain(48, 7, dark_plains_id)
SetWorldMapTileTerrain(48, 8, dark_plains_id)
SetWorldMapTileTerrain(48, 9, dark_plains_id)
SetWorldMapTileTerrain(48, 10, dark_plains_id)
SetWorldMapTileTerrain(48, 11, hills_id)
SetWorldMapTileTerrain(48, 12, hills_id)
SetWorldMapTileTerrain(48, 13, hills_id)
SetWorldMapTileTerrain(48, 14, hills_id)
SetWorldMapTileTerrain(48, 15, hills_id)
SetWorldMapTileTerrain(48, 16, dark_plains_id)
SetWorldMapTileTerrain(49, 0, dark_plains_id)
SetWorldMapTileTerrain(49, 1, dark_plains_id)
SetWorldMapTileTerrain(49, 2, dark_plains_id)
SetWorldMapTileTerrain(49, 3, mountains_id)
SetWorldMapTileTerrain(49, 4, mountains_id)
SetWorldMapTileTerrain(49, 5, hills_id)
SetWorldMapTileTerrain(49, 6, hills_id)
SetWorldMapTileTerrain(49, 7, dark_plains_id)
SetWorldMapTileTerrain(49, 8, dark_plains_id)
SetWorldMapTileTerrain(49, 9, dark_plains_id)
SetWorldMapTileTerrain(49, 10, dark_plains_id)
SetWorldMapTileTerrain(49, 11, dark_plains_id)
SetWorldMapTileTerrain(49, 12, hills_id)
SetWorldMapTileTerrain(49, 13, hills_id)
SetWorldMapTileTerrain(49, 14, hills_id)
SetWorldMapTileTerrain(49, 15, hills_id)
SetWorldMapTileTerrain(49, 16, hills_id)
SetWorldMapTileTerrain(49, 17, dark_plains_id)
SetWorldMapTileTerrain(49, 18, dark_plains_id)
SetWorldMapTileTerrain(50, 1, dark_plains_id)
SetWorldMapTileTerrain(50, 2, dark_plains_id)
SetWorldMapTileTerrain(50, 3, dark_plains_id)
SetWorldMapTileTerrain(50, 4, mountains_id)
SetWorldMapTileTerrain(50, 5, hills_id)
SetWorldMapTileTerrain(50, 6, hills_id)
SetWorldMapTileTerrain(50, 7, hills_id)
SetWorldMapTileTerrain(50, 8, hills_id)
SetWorldMapTileTerrain(50, 9, dark_plains_id)
SetWorldMapTileTerrain(50, 10, dark_plains_id)
SetWorldMapTileTerrain(50, 11, dark_plains_id)
SetWorldMapTileTerrain(50, 12, dark_plains_id)
SetWorldMapTileTerrain(50, 13, hills_id)
SetWorldMapTileTerrain(50, 14, hills_id)
SetWorldMapTileTerrain(50, 15, hills_id)
SetWorldMapTileTerrain(50, 16, hills_id)
SetWorldMapTileTerrain(50, 17, hills_id)
SetWorldMapTileTerrain(50, 18, hills_id)
SetWorldMapTileTerrain(50, 19, dark_plains_id)
SetWorldMapTileTerrain(50, 20, scrub_forest_id)
AddWorldMapResource("lumber", 50, 20, true)
SetWorldMapTileTerrain(51, 3, dark_plains_id)
SetWorldMapTileTerrain(51, 4, mountains_id)
SetWorldMapTileTerrain(51, 5, hills_id)
SetWorldMapTileTerrain(51, 6, hills_id)
SetWorldMapTileTerrain(51, 7, hills_id)
SetWorldMapTileTerrain(51, 8, hills_id)
SetWorldMapTileTerrain(51, 9, hills_id)
SetWorldMapTileTerrain(51, 10, hills_id)
SetWorldMapTileTerrain(51, 11, dark_plains_id)
SetWorldMapTileTerrain(51, 12, dark_plains_id)
SetWorldMapTileTerrain(51, 13, hills_id)
SetWorldMapTileTerrain(51, 14, hills_id)
SetWorldMapTileTerrain(51, 15, hills_id)
AddWorldMapResource("gold", 51, 15, false)
SetWorldMapTileTerrain(51, 16, hills_id)
SetWorldMapTileTerrain(51, 17, hills_id)
SetWorldMapTileTerrain(51, 18, hills_id)
SetWorldMapTileTerrain(51, 19, hills_id)
SetWorldMapTileTerrain(51, 20, hills_id)
SetWorldMapTileTerrain(52, 4, hills_id)
SetWorldMapTileTerrain(52, 5, hills_id)
SetWorldMapTileTerrain(52, 6, hills_id)
SetWorldMapTileTerrain(52, 7, hills_id)
SetWorldMapTileTerrain(52, 8, hills_id)
SetWorldMapTileTerrain(52, 9, hills_id)
SetWorldMapTileTerrain(52, 10, hills_id)
SetWorldMapTileTerrain(52, 11, hills_id)
SetWorldMapTileTerrain(52, 12, dark_plains_id)
SetWorldMapTileTerrain(52, 13, hills_id)
SetWorldMapTileTerrain(52, 14, hills_id)
SetWorldMapTileTerrain(52, 15, hills_id)
SetWorldMapTileTerrain(52, 16, hills_id)
SetWorldMapTileTerrain(52, 17, hills_id)
SetWorldMapTileTerrain(52, 18, hills_id)
SetWorldMapTileTerrain(52, 19, hills_id)
SetWorldMapTileTerrain(52, 20, hills_id)
SetWorldMapTileTerrain(53, 4, dark_plains_id)
SetWorldMapTileTerrain(53, 5, hills_id)
SetWorldMapTileTerrain(53, 6, hills_id)
SetWorldMapTileTerrain(53, 7, hills_id)
SetWorldMapTileTerrain(53, 8, hills_id)
SetWorldMapTileTerrain(53, 9, dark_plains_id)
SetWorldMapTileTerrain(53, 10, dark_plains_id)
SetWorldMapTileTerrain(53, 11, dark_plains_id)
SetWorldMapTileTerrain(53, 12, dark_plains_id)
SetWorldMapTileTerrain(53, 13, hills_id)
SetWorldMapTileTerrain(53, 14, hills_id)
SetWorldMapTileTerrain(53, 15, dark_plains_id)
SetWorldMapTileTerrain(53, 16, hills_id)
SetWorldMapTileTerrain(53, 17, hills_id)
SetWorldMapTileTerrain(53, 18, hills_id)
SetWorldMapTileTerrain(53, 19, hills_id)
SetWorldMapTileTerrain(53, 20, hills_id)
SetWorldMapTileTerrain(54, 6, dark_plains_id)
SetWorldMapTileTerrain(54, 7, dark_plains_id)
SetWorldMapTileTerrain(54, 8, dark_plains_id)
SetWorldMapTileTerrain(54, 9, dark_plains_id)
SetWorldMapTileTerrain(54, 10, dark_plains_id)
SetWorldMapTileTerrain(54, 11, dark_plains_id)
SetWorldMapTileTerrain(54, 12, dark_plains_id)
SetWorldMapTileTerrain(54, 13, hills_id)
SetWorldMapTileTerrain(54, 14, hills_id)
SetWorldMapTileTerrain(54, 15, dark_plains_id)
SetWorldMapTileTerrain(54, 16, hills_id)
SetWorldMapTileTerrain(54, 17, hills_id)
SetWorldMapTileTerrain(54, 18, hills_id)
SetWorldMapTileTerrain(54, 19, hills_id)
SetWorldMapTileTerrain(55, 7, dark_plains_id)
SetWorldMapTileTerrain(55, 8, dark_plains_id)
SetWorldMapTileTerrain(55, 9, dark_plains_id)
SetWorldMapTileTerrain(55, 10, dark_plains_id)
SetWorldMapTileTerrain(55, 11, dark_plains_id)
SetWorldMapTileTerrain(55, 12, dark_plains_id)
SetWorldMapTileTerrain(55, 13, dark_plains_id)
SetWorldMapTileTerrain(55, 14, dark_plains_id)
SetWorldMapTileTerrain(55, 15, dark_plains_id)
SetWorldMapTileTerrain(55, 16, hills_id)
SetWorldMapTileTerrain(55, 17, hills_id)
SetWorldMapTileTerrain(55, 18, hills_id)
SetWorldMapTileTerrain(55, 19, hills_id)
SetWorldMapTileTerrain(56, 12, dark_plains_id)
SetWorldMapTileTerrain(56, 13, dark_plains_id)
SetWorldMapTileTerrain(56, 14, dark_plains_id)
SetWorldMapTileTerrain(56, 15, dark_plains_id)
SetWorldMapTileTerrain(56, 16, dark_plains_id)
SetWorldMapTileTerrain(56, 17, dark_plains_id)
SetWorldMapTileTerrain(56, 18, hills_id)

LoadFactions("Nidavellir")

LoadProvinces("Nidavellir")

-- generate procedural provinces
GenerateProvince({
	Province = WorldMapProvinces.Aurvang,
	BorderProvinces = {"Svarinshaug"},
	BorderProvinceSouth = true,
	Resources = {
		lumber = 3,
		mushrooms = 1
	}
})
GenerateProvince({
	Province = WorldMapProvinces.Joruvellir,
	BorderProvinces = {"Aurvang"},
	BorderProvinceSouth = true,
	Resources = {
		gold = 1,
		lumber = 1,
		mushrooms = 2,
		stone = 2
	}
})
GenerateProvince({
	Province = WorldMapWaterProvinces.DeepSea,
	BorderProvinces = {"Kal Kartha", "Lyr"},
	BorderProvinceEast = true,
	Water = true,
	MaximumSize = 300
})

-- generate resources for provinces
--AddProvinceResource(WorldMapProvinces.BrownHills, "gold", 1)
AddProvinceResource(WorldMapProvinces.BrownHills, "mushrooms", 2)
AddProvinceResource(WorldMapProvinces.BrownHills, "stone", 1)
AddProvinceResource(WorldMapProvinces.CavernsOfChaincolt, "mushrooms", 3)
AddProvinceResource(WorldMapProvinces.CavernsOfChaincolt, "stone", 1)
AddProvinceResource(WorldMapProvinces.CavernsOfFlame, "mushrooms", 1)
AddProvinceResource(WorldMapProvinces.EasternMines, "mushrooms", 1)
AddProvinceResource(WorldMapProvinces.Heartfangs, "mushrooms", 1)
AddProvinceResource(WorldMapProvinces.Heartfangs, "stone", 3)
AddProvinceResource(WorldMapProvinces.HighPass, "mushrooms", 1)
AddProvinceResource(WorldMapProvinces.HighPass, "stone", 1)
AddProvinceResource(WorldMapProvinces.HighbrookPass, "mushrooms", 2)
AddProvinceResource(WorldMapProvinces.HighbrookPass, "stone", 1)
AddProvinceResource(WorldMapProvinces.KalKartha, "mushrooms", 4)
AddProvinceResource(WorldMapProvinces.KalKartha, "stone", 1)
AddProvinceResource(WorldMapProvinces.Lyr, "mushrooms", 3)
AddProvinceResource(WorldMapProvinces.Lyr, "stone", 1)
AddProvinceResource(WorldMapProvinces.NorthernWastelands, "mushrooms", 1)
AddProvinceResource(WorldMapProvinces.NorthernWastelands, "stone", 1)
AddProvinceResource(WorldMapProvinces.PeacefulValley, "mushrooms", 1)
AddProvinceResource(WorldMapProvinces.ShorbearHills, "mushrooms", 2)
AddProvinceResource(WorldMapProvinces.ShorbearHills, "stone", 1)
AddProvinceResource(WorldMapProvinces.SouthernTunnels, "mushrooms", 2)
AddProvinceResource(WorldMapProvinces.SouthernTunnels, "stone", 1)
--AddProvinceResource(WorldMapProvinces.Svarinshaug, "gold", 1)
AddProvinceResource(WorldMapProvinces.Svarinshaug, "mushrooms", 2)
AddProvinceResource(WorldMapProvinces.Svarinshaug, "stone", 1)

MercenaryGroups = {
	unit_surghan_mercenary_steelclad = 4
}

LoadEvents("Nidavellir")

if (GrandStrategyYear >= -3000) then
	SetProvinceHero("Svarinshaug", "Modsognir", "unit-hero-modsognir", 2) 
	SetFactionRuler("dwarf", "Modsogning Clan", "Modsognir")
	SetProvinceHero("Svarinshaug", "Durin", "unit-hero-durin", 2)
	SetProvinceUnitQuantity("Svarinshaug", "unit-dwarven-miner", 4)
	
	-- give plow technology to the dwarven factions
	SetFactionTechnology("dwarf", "Modsogning Clan", "upgrade-dwarven-wood-plow", true)
	SetFactionTechnology("dwarf", "Norlund Clan", "upgrade-dwarven-wood-plow", true)
	SetFactionTechnology("dwarf", "Shinsplitter Clan", "upgrade-dwarven-wood-plow", true)
	SetFactionTechnology("dwarf", "Shorbear Clan", "upgrade-dwarven-wood-plow", true)
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-wood-plow", true)
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-wood-plow", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-wood-plow", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-wood-plow", true)
end

if (GrandStrategyYear >= -2970) then -- estimated date
	GrandStrategyEvents.ARockyHome = nil -- should be placed at an earlier date
	GrandStrategyEvents.TheMeadOfWisdom = nil -- should be placed at an earlier date
	GrandStrategyEvents.TheTreasuresOfSvarinshaug = nil -- should be placed at an earlier date

	GrandStrategyEvents.TheNecklaceOfTheBrisings = nil -- should be placed at an earlier date
	SetProvinceUnitQuantity("Aurvang", "unit-dwarven-steelclad", 0) -- bandits rooted out
	SetProvinceUnitQuantity("Aurvang", "unit-dwarven-axefighter", 0)
	SetProvinceUnitQuantity("Aurvang", "unit-goblin-spearman", 6) -- place some goblins in Aurvang after the dwarven bandits are gone
	SetProvinceUnitQuantity("Aurvang", "unit-goblin-archer", 3)
		
	GrandStrategyEvents.TheBindingOfGrafvitnir = nil -- should be placed at an earlier date
	SetProvinceHero("Svarinshaug", "Modsognir", "unit-hero-modsognir", 0)
	SetProvinceHero("Svarinshaug", "Durin", "unit-hero-durin", 0)
end

if (GrandStrategyYear >= -1) then
	GrandStrategyEvents.TheNorlundClan = nil
	GrandStrategyEvents.TheShinsplitterClan = nil
	GrandStrategyEvents.TheShorbearClan = nil
	SetProvinceOwner("Caverns of Chaincolt", "dwarf", "Norlund Clan")
	SetProvinceUnitQuantity("Caverns of Chaincolt", "unit-dwarven-miner", 4)
	SetProvinceSettlementBuilding("Caverns of Chaincolt", "unit-dwarven-town-hall", true)
	SetProvinceSettlementBuilding("Caverns of Chaincolt", "unit-dwarven-barracks", true) -- has capability to train warriors
	SetProvinceSettlementBuilding("Caverns of Chaincolt", "unit-dwarven-smithy", true) -- Durstorn has runesmiths under his employ
	SetProvinceUnitQuantity("Caverns of Chaincolt", "unit-goblin-spearman", 0)
--	SetProvinceUnitQuantity("Caverns of Chaincolt", "unit-dwarven-steelclad", 4) -- Neglur, Glinar, Kuhnar, Theganli
--	SetProvinceUnitQuantity("Caverns of Chaincolt", "unit-dwarven-scout", 1) -- Noiraran
	SetProvinceUnitQuantity("Caverns of Chaincolt", "unit-dwarven-axefighter", 4) -- 4 Dwarven Guardsmen (5 if easy mode)
	SetProvinceUnitQuantity("Caverns of Chaincolt", "unit-dwarven-steelclad", 2) -- Neglur, Glinar
	SetWorldMapResourceProspected("gold", 30, 12, true)
	SetProvinceOwner("Shorbear Hills", "dwarf", "Shorbear Clan")
	SetProvinceSettlementBuilding("Shorbear Hills", "unit-dwarven-town-hall", true)
	SetProvinceSettlementBuilding("Shorbear Hills", "unit-dwarven-stronghold", true) -- Shorbear Hold
	SetProvinceSettlementBuilding("Shorbear Hills", "unit-dwarven-barracks", true) -- has capability to train warriors
	SetProvinceSettlementBuilding("Shorbear Hills", "unit-dwarven-smithy", true) -- renowned skilled crafters
	SetProvinceUnitQuantity("Shorbear Hills", "unit-goblin-spearman", 0)
	SetProvinceUnitQuantity("Shorbear Hills", "unit-dwarven-thane", 1) -- Glonoin
	SetFactionRuler("dwarf", "Shorbear Clan", "Glonoin")
	SetProvinceUnitQuantity("Shorbear Hills", "unit-dwarven-miner", 4)
	SetWorldMapResourceProspected("gold", 34, 14, true)
	SetProvinceOwner("Southern Tunnels", "dwarf", "Shinsplitter Clan")
	SetProvinceSettlementBuilding("Southern Tunnels", "unit-dwarven-town-hall", true)
	SetProvinceSettlementBuilding("Southern Tunnels", "unit-dwarven-barracks", true) -- has capability to train warriors
	SetProvinceUnitQuantity("Southern Tunnels", "unit-goblin-spearman", 0)
	SetProvinceUnitQuantity("Southern Tunnels", "unit-dwarven-steelclad", 3) -- Glildur, Glindur, Kalnar
	SetProvinceUnitQuantity("Southern Tunnels", "unit-dwarven-thane", 5) -- Lyndar, Gaenlar, Glinan, Crintil, Aendan
	SetProvinceUnitQuantity("Southern Tunnels", "unit-dwarven-miner", 4)
	SetWorldMapResourceProspected("gold", 32, 13, true)

	-- bronze age technologies had already been obtained by the dwarves by this point
	SetFactionTechnology("dwarf", "Modsogning Clan", "upgrade-dwarven-broad-axe", true)
	SetFactionTechnology("dwarf", "Modsogning Clan", "upgrade-dwarven-shield-1", true)
	SetFactionTechnology("dwarf", "Modsogning Clan", "upgrade-dwarven-throwing-axe-1", true)
	SetFactionTechnology("dwarf", "Norlund Clan", "upgrade-dwarven-broad-axe", true)
	SetFactionTechnology("dwarf", "Norlund Clan", "upgrade-dwarven-shield-1", true)
	SetFactionTechnology("dwarf", "Norlund Clan", "upgrade-dwarven-throwing-axe-1", true)
	SetFactionTechnology("dwarf", "Shinsplitter Clan", "upgrade-dwarven-broad-axe", true)
	SetFactionTechnology("dwarf", "Shinsplitter Clan", "upgrade-dwarven-shield-1", true)
	SetFactionTechnology("dwarf", "Shinsplitter Clan", "upgrade-dwarven-throwing-axe-1", true)
	SetFactionTechnology("dwarf", "Shorbear Clan", "upgrade-dwarven-broad-axe", true)
	SetFactionTechnology("dwarf", "Shorbear Clan", "upgrade-dwarven-shield-1", true)
	SetFactionTechnology("dwarf", "Shorbear Clan", "upgrade-dwarven-throwing-axe-1", true)
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-broad-axe", true)
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-shield-1", true)
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-throwing-axe-1", true)
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-broad-axe", true)
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-shield-1", true)
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-throwing-axe-1", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-broad-axe", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-shield-1", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-throwing-axe-1", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-broad-axe", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-shield-1", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-throwing-axe-1", true)
	
	SetProvinceHero("Caverns of Chaincolt", "Durstorn", "unit-hero-durstorn", 2) -- Durstorn was already present when the conflict with Pypo over the Brown Hills happened
	SetFactionRuler("dwarf", "Norlund Clan", "Durstorn")
	SetProvinceHero("Caverns of Chaincolt", "Baglur", "unit-hero-baglur", 2) -- Baglur was already present when the conflict with Pypo over the Brown Hills happened
	SetProvinceHero("Caverns of Chaincolt", "Thursagan", "unit-hero-thursagan", 2) -- Thursagan could be in the Caverns of Chaincolt at this time
	
	SetFactionRuler("gnome", "Untersberg", "Pypo")
end

if (GrandStrategyYear >= 25) then -- at this time Rugnur was already in charge of the outpost in the Chaincolt Foothills, Baglur was at the Caverns of Chaincolt gate, Thursagan was living in the Northern Wastelands and Durstorn was the chief of the Norlund clan
	SetProvinceHero("Caverns of Chaincolt", "Rugnur", "unit-hero-rugnur", 2)
	SetProvinceHero("Northern Wastelands", "Thursagan", "unit-hero-thursagan", 2) -- by this point, Thursagan had gone away to the north
	GrandStrategyEvents.TheSagesDeparture = nil

	SetProvinceSettlementBuilding("Caverns of Chaincolt", "unit-dwarven-lumber-mill", true) -- had capability to train scouts by then
	SetProvinceSettlementBuilding("Southern Tunnels", "unit-dwarven-lumber-mill", true) -- had capability to train scouts by then

	-- dwarves already had castles built of stone masonry by then
	SetFactionTechnology("dwarf", "Modsogning Clan", "upgrade-dwarven-masonry", true)
	SetFactionTechnology("dwarf", "Norlund Clan", "upgrade-dwarven-masonry", true)
	SetFactionTechnology("dwarf", "Shinsplitter Clan", "upgrade-dwarven-masonry", true)
	SetFactionTechnology("dwarf", "Shorbear Clan", "upgrade-dwarven-masonry", true)
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-masonry", true)
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-masonry", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-masonry", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-masonry", true)
end

if (GrandStrategyYear > 25) then
	GrandStrategyEvents.StrikeABargain = nil
	GrandStrategyEvents.ABargainIsStruckShinsplitterClan = nil
	GrandStrategyEvents.ClosingTheGates = nil
	GrandStrategyEvents.ClosingTheGatesShinsplitterClan = nil
	SetProvinceUnitQuantity("Caverns of Chaincolt", "unit-gnomish-recruit", 1)
	SetFactionDiplomacyState("dwarf", "Norlund Clan", "dwarf", "Shinsplitter Clan", "war")
	ChangeFactionResource("gnome", "Untersberg", "gold", -2500) -- decrease gnomish treasury by 5000 silver (considering for our purposes silver to be worth half as much as gold)
	ChangeFactionResource("dwarf", "Norlund Clan", "gold", 2500) -- 5000 silver, and for our purposes silver is considered to be worth half of what gold is
	ChangeProvinceUnitQuantity("Southern Tunnels", "unit-dwarven-steelclad", -1)
end

if (GrandStrategyYear >= 27) then -- time it took for Rugnur's party to travel to the Northern Wastelands and come back
	GrandStrategyEvents.SearchingForTheRunecrafter = nil
	SetProvinceHero("Caverns of Chaincolt", "Thursagan", "unit-hero-thursagan", 2)
	SetProvinceSettlementBuilding("Northern Wastelands", "unit-dwarven-smithy", false) -- Thursagan abandoned his smithy in the Northern Wastelands to follow Rugnur is his quest to craft the Scepter of Fire
--	ChangeProvinceUnitQuantity("Caverns of Chaincolt", "unit-dwarven-steelclad", 2) -- Thursagan joined and brought Kinan and Rynan, two runecrafters-in-training
	SetProvinceUnitQuantity("Northern Wastelands", "unit-goblin-spearman", GetProvinceUnitQuantity("Northern Wastelands", "unit-goblin-spearman") / 2) -- halve enemies in the northern wastelands (deaths due to combat with Rugnur's dwarves)
	SetProvinceUnitQuantity("Northern Wastelands", "unit-goblin-archer", GetProvinceUnitQuantity("Northern Wastelands", "unit-goblin-archer") / 2)
	SetProvinceUnitQuantity("Caverns of Chaincolt", "unit-dwarven-gryphon-rider", 2) -- two gryphon riders joined from the travel to the Northern Wastelands
end

if (GrandStrategyYear >= 29) then
	GrandStrategyEvents.GatheringMaterials = nil
	ChangeFactionResource("dwarf", "Norlund Clan", "coal", 20000) -- Rugnur's party returned from the Eastern Mines in 29 AD
--	SetProvinceUnitQuantity("Eastern Mines", "unit-goblin-spearman", GetProvinceUnitQuantity("Eastern Mines", "unit-goblin-spearman") / 2)
	SetProvinceUnitQuantity("Eastern Mines", "unit-goblin-spearman", 12) -- to prevent the Norlunds expanding here too soon
	SetProvinceUnitQuantity("Eastern Mines", "unit-goblin-archer", 4)
	SetWorldMapResourceProspected("gold", 39, 6, true) -- Rugnur and his companions found the location of the gold mines in the Eastern Mines

	--[[
	SetProvinceOwner("Shorbear Hills", "dwarf", "Norlund Clan") -- Shorbear Hold conquered in 29 AD by Rugnur's and Durstorn's Clan (Norlund Clan)
	SetProvinceHero("Shorbear Hills", "Rugnur", "unit-hero-rugnur", 2)
	SetProvinceHero("Shorbear Hills", "Baglur", "unit-hero-baglur", 2)
	SetProvinceHero("Shorbear Hills", "Durstorn", "unit-hero-durstorn", 2)
	SetProvinceHero("Shorbear Hills", "Thursagan", "unit-hero-thursagan", 2)
	--]]
	KillGrandStrategyHero("Glonoin")

	SetProvinceSettlementBuilding("Shorbear Hills", "unit-dwarven-lumber-mill", true) -- had capability to train scouts by then
end

if (GrandStrategyYear >= 35) then
	GrandStrategyEvents.HillsOfTheShorbearClan = nil
	GrandStrategyEvents.HillsOfTheShorbearClanShinsplitterClan = nil
	GrandStrategyEvents.HillsOfTheShorbearClanShorbearClan = nil
	SetProvinceOwner("Shorbear Hills", "dwarf", "Shinsplitter Clan") -- Shorbear Hold abandoned in 35 AD by Rugnur's and Durstorn's Clan (Norlund Clan), while the Shinsplitter forces were sieging them
	SetProvinceUnitQuantity("Shorbear Hills", "unit-dwarven-axefighter", 0)
	SetProvinceUnitQuantity("Shorbear Hills", "unit-dwarven-thane", 0)
	--[[
	SetProvinceHero("Caverns of Flame", "Rugnur", "unit-hero-rugnur", 2)
	SetProvinceHero("Caverns of Flame", "Baglur", "unit-hero-baglur", 2)
	SetProvinceHero("Caverns of Flame", "Thursagan", "unit-hero-thursagan", 2)
	--]]
	SetProvinceHero("Shorbear Hills", "Durstorn", "unit-hero-durstorn", 0) -- Durstorn is killed in a conflict between him and other members of the clan
	SetProvinceSettlementBuilding("Southern Tunnels", "unit-mercenary-camp", true) -- at some point between 35 and 40 AD the Shinsplitters had the capacity to recruit mercenaries, as shown by them having hired the Surghan Mercenaries
	MercenaryGroups.unit_surghan_mercenary_steelclad = nil
	SetProvinceUnitQuantity("Caverns of Chaincolt", "unit-gnomish-recruit", 0) -- gnomish recruit returns to Untersberg
	SetProvinceUnitQuantity("Caverns of Chaincolt", "unit-dwarven-gryphon-rider", 0) -- gryphon riders return to the Northern Wastelands
end

if (GrandStrategyYear >= 40) then
	SetProvinceHero("Caverns of Chaincolt", "Rugnur", "unit-hero-rugnur", 0) -- Rugnur, Baglur and Thursagan die at the Caverns of Flame
	SetProvinceHero("Caverns of Chaincolt", "Baglur", "unit-hero-baglur", 0)
	SetProvinceHero("Caverns of Chaincolt", "Thursagan", "unit-hero-thursagan", 0)
	ChangeFactionResource("dwarf", "Norlund Clan", "coal", -20000) -- Scepter of Fire crafted
	ChangeFactionResource("dwarf", "Norlund Clan", "gold", 2500) -- payment for the crafting of the Scepter
	ChangeFactionResource("gnome", "Untersberg", "gold", -2500) -- payment for the crafting of the Scepter
	SetProvinceOwner("Shorbear Hills", "dwarf", "Norlund Clan") -- Shorbear Hold ceded by the Shinsplitters to the Norlunds and peace established
	SetFactionDiplomacyState("dwarf", "Norlund Clan", "dwarf", "Shinsplitter Clan", "peace")
	KillGrandStrategyHero("Pypo")
end

if (GrandStrategyYear >= 389) then
	SetProvinceOwner("Peaceful Valley", "", "") -- Lggi Tribe destroyed
	SetProvinceCivilization("Peaceful Valley", "")
	SetProvinceUnitQuantity("Peaceful Valley", "unit-goblin-spearman", 0)
	SetProvinceSettlementBuilding("Peaceful Valley", "unit-goblin-town-hall", false)
	SetProvinceSettlementBuilding("Peaceful Valley", "unit-goblin-barracks", false)
end

if (GrandStrategyYear >= 400) then
	SetProvinceOwner("Caverns of Chaincolt", "dwarf", "Knalga") -- The Lordship of Knalga was founded around 400 AD
	SetProvinceOwner("Southern Tunnels", "dwarf", "Knalga")
	SetProvinceOwner("Shorbear Hills", "dwarf", "Knalga")
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-runewriting", true) -- polities require writing

	SetProvinceOwner("Kal Kartha", "dwarf", "Kal Kartha") -- The Lordship of Kal Kartha was founded around 400 AD
	SetProvinceSettlementBuilding("Kal Kartha", "unit-dwarven-town-hall", true)
	SetProvinceSettlementBuilding("Kal Kartha", "unit-dwarven-barracks", true)
	SetProvinceUnitQuantity("Kal Kartha", "unit-gnomish-recruit", 0)
	SetWorldMapResourceProspected("gold", 46, 5, true)
	SetProvinceUnitQuantity("Kal Kartha", "unit-dwarven-miner", 4)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-runewriting", true) -- polities require writing

	SetProvinceOwner("Lyr", "dwarf", "Lyr") -- The Lordship of Lyr was founded around the same time as the other lordships
	SetProvinceSettlementBuilding("Lyr", "unit-dwarven-town-hall", true)
	SetProvinceSettlementBuilding("Lyr", "unit-dwarven-barracks", true)
	SetProvinceUnitQuantity("Lyr", "unit-dwarven-axefighter", 0)
	SetWorldMapResourceProspected("gold", 51, 15, true)
	SetProvinceUnitQuantity("Lyr", "unit-dwarven-miner", 4)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-runewriting", true) -- polities require writing
	
	SetProvinceOwner("Joruvellir", "dwarf", "Joruvellir") -- The Lordship of Joruvellir may have been founded at the same time as the other lordships
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-runewriting", true) -- polities require writing
	SetProvinceSettlementBuilding("Joruvellir", "unit-dwarven-town-hall", true)
	SetProvinceUnitQuantity("Joruvellir", "unit-goblin-spearman", 0)
	SetProvinceUnitQuantity("Joruvellir", "unit-goblin-archer", 0)

	-- The Dwarves should already have Coinage technology by then
	SetFactionTechnology("dwarf", "Modsogning Clan", "upgrade-dwarven-coinage", true)
	SetFactionTechnology("dwarf", "Norlund Clan", "upgrade-dwarven-coinage", true)
	SetFactionTechnology("dwarf", "Shinsplitter Clan", "upgrade-dwarven-coinage", true)
	SetFactionTechnology("dwarf", "Shorbear Clan", "upgrade-dwarven-coinage", true)
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-coinage", true)
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-coinage", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-coinage", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-coinage", true)
end

if (GrandStrategyYear >= 500) then
	SetProvinceOwner("Highbrook Pass", "dwarf", "Shinsplitter Clan") -- The Shinsplitter clan took over the Highbrook Pass around this time
	SetProvinceSettlementBuilding("Highbrook Pass", "unit-dwarven-town-hall", true)
	SetProvinceUnitQuantity("Highbrook Pass", "unit-goblin-spearman", 0)
	SetProvinceUnitQuantity("Highbrook Pass", "unit-goblin-archer", 0)
	SetProvinceUnitQuantity("Highbrook Pass", "unit-dwarven-axefighter", 6) -- six dwarven ulfserkers
	SetProvinceUnitQuantity("Highbrook Pass", "unit-dwarven-thane", 1) -- Stalrag
	SetWorldMapResourceProspected("gold", 35, 10, true)
end

if (GrandStrategyYear >= 534) then
	SetProvinceUnitQuantity("Southern Tunnels", "unit-dwarven-steelclad", 4) -- 4 Dwarven Stalwarts
	SetProvinceUnitQuantity("Southern Tunnels", "unit-dwarven-thane", 1) -- Hamel

	-- Mushroom Farms existent in Knalga
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-iron-tipped-wood-plow", true)
	
	-- let's set plow upgrades for the other dwarven polities now too
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-iron-tipped-wood-plow", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-iron-tipped-wood-plow", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-iron-tipped-wood-plow", true)
end

if (GrandStrategyYear >= 535) then
	SetProvinceSettlementBuilding("Highbrook Pass", "unit-dwarven-barracks", true) -- the Shinsplitters were already capable of recruiting warriors in Highbrook Pass around this time
end

if (GrandStrategyYear >= 550) then
	SetProvinceSettlementBuilding("Kal Kartha", "unit-dwarven-smithy", true) -- Karrag was already reviving the art of runesmithing in 550 AD

	SetProvinceUnitQuantity("Kal Kartha", "unit-dwarven-axefighter", 2) -- 2 Masked Ulfserkers in Karrag's court
	SetProvinceUnitQuantity("Kal Kartha", "unit-dwarven-steelclad", 3) -- Dulcatulos, 2 Masked Steelclads in Karrag's court
	SetProvinceUnitQuantity("Kal Kartha", "unit-dwarven-thane", 4) -- Karrag
	
	-- late iron age technologies already obtained by the dwarves by this point
	SetFactionTechnology("dwarf", "Modsogning Clan", "upgrade-dwarven-great-axe", true)
	SetFactionTechnology("dwarf", "Modsogning Clan", "upgrade-dwarven-shield-2", true)
	SetFactionTechnology("dwarf", "Modsogning Clan", "upgrade-dwarven-throwing-axe-2", true)
	SetFactionTechnology("dwarf", "Modsogning Clan", "upgrade-dwarven-ballista-bolt-1", true)
	SetFactionTechnology("dwarf", "Norlund Clan", "upgrade-dwarven-great-axe", true)
	SetFactionTechnology("dwarf", "Norlund Clan", "upgrade-dwarven-shield-2", true)
	SetFactionTechnology("dwarf", "Norlund Clan", "upgrade-dwarven-throwing-axe-2", true)
	SetFactionTechnology("dwarf", "Norlund Clan", "upgrade-dwarven-ballista-bolt-1", true)
	SetFactionTechnology("dwarf", "Shinsplitter Clan", "upgrade-dwarven-great-axe", true)
	SetFactionTechnology("dwarf", "Shinsplitter Clan", "upgrade-dwarven-shield-2", true)
	SetFactionTechnology("dwarf", "Shinsplitter Clan", "upgrade-dwarven-throwing-axe-2", true)
	SetFactionTechnology("dwarf", "Shinsplitter Clan", "upgrade-dwarven-ballista-bolt-1", true)
	SetFactionTechnology("dwarf", "Shorbear Clan", "upgrade-dwarven-great-axe", true)
	SetFactionTechnology("dwarf", "Shorbear Clan", "upgrade-dwarven-shield-2", true)
	SetFactionTechnology("dwarf", "Shorbear Clan", "upgrade-dwarven-throwing-axe-2", true)
	SetFactionTechnology("dwarf", "Shorbear Clan", "upgrade-dwarven-ballista-bolt-1", true)
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-great-axe", true)
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-shield-2", true)
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-throwing-axe-2", true)
	SetFactionTechnology("dwarf", "Joruvellir", "upgrade-dwarven-ballista-bolt-1", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-great-axe", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-shield-2", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-throwing-axe-2", true)
	SetFactionTechnology("dwarf", "Kal Kartha", "upgrade-dwarven-ballista-bolt-1", true)
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-great-axe", true)
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-shield-2", true)
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-throwing-axe-2", true)
	SetFactionTechnology("dwarf", "Knalga", "upgrade-dwarven-ballista-bolt-1", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-great-axe", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-shield-2", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-throwing-axe-2", true)
	SetFactionTechnology("dwarf", "Lyr", "upgrade-dwarven-ballista-bolt-1", true)
end